containerd/nydus-snapshotter

misc/snapshotter/Dockerfile, misc/snapshotter/entrypoint.sh
A few improvements for the nydus-snapshotter image.
1. support customized containerd root path
2. use shared daemon mode
3. handle base image CA issue
4. do not install recommended packages
5. clean up apt cache
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> improve nydus snapshotter container image

.github/workflows/image.yml, misc/snapshotter/Dockerfile
* `nydus-snapshotter:latest` is built and pushed on each push to main
* `nydus-snapshotter:$release_tag` is built and pushed on each release tag
* `nydus-snapshotter:local` is built on each pull request but not pushed, for testing purpose
Tested at https://github.com/bergwolf/nydus-snapshotter/actions/workflows/image.yml
=> fix image builder ssl issue and trigger build on pull_request and release

README.md, cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, go.mod
Remove nydusd-path and nydusimg-path from startup options,
instead lookup them in PATH.
Fixes: #8
=> cmd: remove nydusd-path and nydusimg-path startup options

README.md
As 'containerd config default' produce default configuration
which include disable_snapshot_annotations=true, but nydus-snapshotter
depend on snapshot annotation, so here we should set explicitly.
Signed-off-by: luodaowen.backend <luodaowen.backend@bytedance.com>
=> README.md: add disable_snapshot_annotations=false in cri env

Makefile, README.md, cmd/containerd-nydus-grpc/pkg/command/flags.go, misc/snapshotter/nydus-snapshotter.service
Users just perform `make install` and download `nydusd` and `nydus-image` before they can use nydus-snapshotter
=> Provide make install to facilitate configuring nydus-snapshotter 

pkg/nydussdk/client.go
So that we know where does that error come from, and make debug easier.
Fixes: #26
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> pkg/nydussdk: add more context on returning errors

pkg/daemon/daemon.go, pkg/metric/serve.go, pkg/process/manager.go
Currently we create new nydusd client in CheckStatus(), SharedMount()
and SharedUmount(), but set max connection in underlying transport to
10. So we sometimes see 503 response when the number of connections
exceed 10.
So let's use one nydus client per Daemon to avoid such 503 error.
Fixes: #31
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> daemon: use one nydus client per Daemon

pkg/daemon/daemon.go, pkg/filesystem/nydus/fs.go, pkg/filesystem/stargz/fs.go, pkg/nydussdk/client.go, pkg/nydussdk/client_test.go, pkg/nydussdk/model/model.go, pkg/process/manager.go
Due to history reason, the daemon state returned by nydusd sock API
has been changed from `Running` to `RUNNING`, the fixup keeps compatibility
and fix nil error return on checking.
=> Fix daemon state check

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, pkg/daemon/config.go, pkg/daemon/daemon.go, pkg/filesystem/nydus/fs.go, pkg/nydussdk/client.go, pkg/process/manager.go, snapshot/snapshot.go
1.  When writing daemon status to nydus.db, json serialization will only
recognize member variables starting with uppercase letters, and
lowercase ones will be ignored. We change these previously ignored ones
to uppercase.
2. Previously, the Close() interface of nydus snapshotter performed Cleanup()
on the filesystem. This behavior is not universal. In fact, on the
contrary, in most cases, the default behavior of Close() should not affect
the existing filesystem so that the filesystem can still work normally
after Reconnect(). While in some special scenarios, the filesystem needs to
be cleaned up with the close of the snapshotter.
So we add introduce a new config option called 'cleanup_on_close' to
control whether to clean up the filesystem under the nydus snapshotter when
the snapshotter …
=> 1. fix the bug that daemon status is not fully serialized; 2. add cleanup_on_close config option; 3. add StatusCode in handleMountError

pkg/converter/convert.go, pkg/converter/utils.go
The current `Convert` implementation has the following interface:
```
Convert(ctx context.Context, dest io.Writer, opt ConvertOption) (src io.WriteCloser, err error)
```
The caller writes the OCI tar stream to src and Convert converts
src to a nydus tar stream and writes it to dest.
The current implementation must wait for the OCI tar stream to be
unpacked into a directory before calling the builder (nydus-image)
to start the build, which takes advantage of `pr, pw := io.Pipe()`.
Before this commit, the `unpackOciTar` method did not fully read
the OCI tarball when `pw.Close()` was called, which means that the
build is started before the unpacking is complete, which may result
in some files being missing from the nydus image.
Fixup: use a channel to wait for the unpack to complete. …
=> converter: fix incomplete unpack

.github/workflows/ci.yml, .github/workflows/image.yml, go.mod, go.sum, misc/example/README.md, misc/snapshotter/Dockerfile, pkg/converter/convert.go, pkg/converter/tool/builder.go, pkg/converter/utils.go
In the previous convert implementation, the builder (nydus-image) would
dump the blob and bootstrap, and then the converter would pack the two
files into a tar format, which has a performance loss, this patch solves this
problem by introducing fifo file.
The converter creates a fifo file, the builder will write the blob and
bootstrap data to the fifo as the writer side, then the converter read
from the fifo and write directly to content store for faster conversion.
Related PR: https://github.com/dragonflyoss/image-service/pull/415
=> converter: improve pack performance by fifo

.github/workflows/ci.yml, Makefile, go.mod, pkg/converter/convert_unix.go, pkg/converter/convert_windows.go, pkg/converter/types.go, pkg/utils/mount/mount_linux.go, pkg/utils/mount/mount_other.go, snapshot/snapshot.go, snapshot/snapshot_darwin.go, snapshot/snapshot_linux.go, snapshot/snapshot_other.go
We need to ensure the snapshotter can be cross-compiled across all
platforms, and although we currently only support linux. We must
make sure that external projects (such as buildkit) are not affected
by cross-compiling when they import package such as `converter`.
=> makefile: ensure cross-compilation compatibility

.github/workflows/release.yml
Users can use this shasum file to verify the validity of
the downloaded nydus snapshotter released tarball file.
=> action: add sha256sum file for release assets

config/config.go, pkg/filesystem/nydus/config.go, pkg/filesystem/nydus/config_test.go, snapshot/snapshot.go
When using DaemonMode = none, nydusd and nydus-image binaries are not
required.
=> daemon: ignore checks for nydus binary when DaemonMode=none

config/daemonconfig.go, config/daemonconfig_test.go
Add `skip_verify: true` option to enable skipping SSL certificate
validation of HTTPS scheme for registry/oss backend.
=> config: support skip_verify backend option

config/daemonconfig.go, config/daemonconfig_test.go
Add `skip_verify: true` option to enable skipping SSL certificate
validation of HTTPS scheme for registry/oss backend.
=> [for stable/v0.2.x] config: support skip_verify backend option

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, config/daemonconfig.go, pkg/cache/manager.go, pkg/daemon/config.go, pkg/daemon/daemon.go, pkg/filesystem/nydus/config.go, pkg/filesystem/nydus/fs.go, pkg/filesystem/stargz/fs.go, pkg/nydussdk/client.go, pkg/process/manager.go, pkg/utils/erofs/erofs_linux.go, pkg/utils/erofs/erofs_other.go, snapshot/snapshot.go
Ref: https://github.com/dragonflyoss/image-service/blob/master/docs/nydus-fscache.md
Add boot option `--daemon-backend erofs` for snapshotter to support
erofs with fscache daemon (nydusd daemon subcommand).
This daemon backend must be used with shared daemon mode, so a general
command usage should like this:
```
containerd-nydus-grpc \
--config-path //path/to/nydus-erofs-config.json \
--daemon-mode shared \
--daemon-backend fscache \
--log-level info \
--root /var/lib/containerd/io.containerd.snapshotter.v1.nydus \
--cache-dir /var/lib/nydus/cache \
--address /run/containerd/containerd-nydus-grpc.sock \
--nydusd-path /usr/bin/nydusd \
--nydusimg-path /usr/bin/nydus-image \
--log-to-stdout
```
=> add support for erofs with fscache

pkg/filesystem/nydus/fs.go
At present, snapshotter download bootstarp requires containerd to pass the auth information over,
this is not currently solved, so temporarily turn off this function.
Signed-off-by: zyfjeff <zyfjeff@linux.alibaba.com>
=> Disable the logic for downloading bootstarp in snapshotter

pkg/process/manager.go
Log-level settings not work for fscache so add "--log-level" in fscache args to fix it.
=> fscache: enable log-level settings

README.md
The argument `container id` is needed when use `ctr-remote run` to run a container.
Signed-off-by: Nan Li <loheagn@icloud.com>
=> doc: provide `container id` when use `ctr-remote run`

pkg/utils/erofs/erofs_linux.go
Since kernel commit ba73eadd23d1 ("erofs: scan devices from device
table"), we don't need "device=" options any more.
Signed-off-by: Gao Xiang \<hsiangkao@linux.alibaba.com\>
=> erofs: drop "device=" options

.gitignore, cmd/containerd-nydus-grpc/main.go, cmd/containerd-nydus-grpc/pkg/command/flags.go, cmd/containerd-nydus-grpc/pkg/logging/setup.go, config/config.go
There are three log related parameters, namely LogLevel, LogDir and
LogToStdout.
Previously, both LogDir and LogToStdout are directly passed to
nydusd daemon, while LogLevel is shared by snapshotter and
nydusd daemon, so actually we can't control the output direction and
file path of the snapshotter log. Now we fix it.
In order to prevent the already running business from being affected on
a large scale, we will not modify the log control method of nydusd
daemon here and continue to let nydusd share the configuration of log
with snapshotter.
Now the default path of nydusd log is (if DaemonMode is not none):
/PATH/TO/ROOTDIR/logs/NYDUSD_DAEMON_ID/stderr.log
And the default path of snapshotter log is:
/PATH/TO/ROOTDIR/logs/nydus-snapshotter.log
Signed-off-by: zhaoshang …
=> log: fix logdir and output bug of snapshotter

.github/workflows/ci.yml, Makefile, pkg/converter/tool/builder.go, tests/converter_test.go, tests/nydusd.go
1. add nydus v6 fs version support
2. add nydus v6 tests
Signed-off-by: zyfjeff <zyfjeff@linux.alibaba.com>
=> Convert: support nydus v6 fs version convert

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, snapshot/snapshot.go
According to the usage of boolflag, the default value should
be false. While async-remove is enabled by default, so we modify args
to sync-remove.
=> args: change async-remove to sync-remove

.github/workflows/image.yml, .gitignore, cmd/containerd-nydus-grpc/app/snapshotter/main.go, cmd/containerd-nydus-grpc/app/snapshotter/serve.go, misc/snapshotter/Dockerfile, misc/snapshotter/entrypoint.sh, misc/snapshotter/nydusd-config-localfs.json, pkg/filesystem/fs/fs.go, pkg/filesystem/nydus/blob_manager.go, pkg/filesystem/nydus/blob_manager_test.go, pkg/filesystem/nydus/config.go, pkg/filesystem/nydus/fs.go, pkg/filesystem/stargz/fs.go, snapshot/snapshot.go
Ref: #48 
When the backend type in the daemon config is localfs, the snapshotter will automatically download the blob layer to the cache directory.
Signed-off-by: zyfjeff <tianqian.zyf@alibaba-inc.com>
=> Implement blob layer download in snapshotter

go.mod, go.sum, pkg/auth/keychain.go, pkg/filesystem/stargz/fs.go, pkg/filesystem/stargz/resolver.go, pkg/filesystem/stargz/resolver_test.go
```
Estargz layer format has changed a lot, the previous method of parsing
TOC data no longer works for new estargz image, so we can directly import
the estargz package to implement the TOC data parsing.
Since tests are also obsolete, they are removed from the test cases.
```
=> Filesystem: fix parsing estargz TOC data

.github/workflows/image.yml, cmd/containerd-nydus-grpc/pkg/command/flags.go, misc/snapshotter/entrypoint.sh, pkg/daemon/daemon.go, pkg/filesystem/fs/fs.go, pkg/filesystem/fs/stargz/resolver.go, pkg/filesystem/meta/meta.go, pkg/utils/registry/registry.go, snapshot/snapshot.go
This is an earlier, experimental version of nydus snapshotter that
implements the ability to run estargz images directly in nydusd
(in user space) or erofs with fscache (in kernel space).
In snapshot prepare stage, we need to convert estargz TOC file
to nydus bootstrap, and in snapshot mount stage, need to merge
all bootstraps into final bootstrap, nydusd will use this it to
mount filesystem.
=> Filesytem: support estargz for rafs v6

pkg/label/label.go, snapshot/snapshot.go
cri callers can add containerd.io/snapshot.volatile annotation to make
corresponding snapshot volatile when mounted to rootfs.
Overlayfs volatile mount is a new feature with Linux 5.10, for more
details: https://www.redhat.com/sysadmin/container-volatile-overlay-mounts
=> Overlayfs: add volatile option when creating Active snapshot

.github/workflows/ci.yml, pkg/converter/convert_unix.go, pkg/converter/convert_windows.go, pkg/converter/tool/builder.go, pkg/converter/types.go, tests/converter_test.go
BACKGROUND
OCI layer is convertible into bootstrap and blob of NYDUS. However there is no way to convert bootstrap and blob to OCI layer.
REQUIREMENT
BuildKit already provides ability to convert OCI layer to NYDUS files. It seeks for the ability to convert back.
FEATURE
Excluding hard link, the hash digests of result and original OCI tar are same .
Including hard link, the unpack result of result and original OCI tar are same.
=> feat: NYDUS files are convertible to OCI tar

pkg/daemon/daemon.go, pkg/errdefs/errors.go
When snapshotter exits (either normally or abnormally), it will not have a
chance to umount erofs mountpoint, so if snapshotter resumes running and mount
again (by a new request to create container), it will need to ignore the mount
error `device or resource busy`.
=> fscache: simple fixup for busy mountpoint

pkg/daemon/daemon.go, pkg/filesystem/fs/fs.go, pkg/filesystem/meta/meta.go
Before this patch, we share the same fscache workdir for all estargz
images, this workdir stores all blob meta files for each estargz image.
The fatal problem is that once an estargz image is removed by user, the
all blob meta files will be cleaned by containerd GC, this behavior affects
all existing estargz images.
This patch stores the blob meta files into each snapshot dir, and then
copy them into topmost snapshot dir if user wants to run a container.
=> fscache: fix fscache workdir path for estargz

go.mod, go.sum, pkg/filesystem/fs/fs.go, pkg/filesystem/fs/resolver.go
Previously, our snapshot will download the image through the go standard http
client, if the http download fails and does not do a retry. Now we retry
for defaultRetryMax = 4 times.
Fixes: #54
=> resolver: replace standard http client to go-retryablehttp

pkg/converter/convert_unix.go, pkg/converter/tool/builder.go, pkg/converter/types.go, tests/converter_test.go
Allow caller to specify the `WorkDir`, `BuilderPath` options,
instead of getting only from environment variable.
Change option name `RafsVersion` to `FsVersion`, make it consistent
with `nydus-image create --fs-version` command.
Add a new `Compressor` option to support more compression algorithms
for pack command.
=> converter: enhance pack/merge/unpack options

pkg/converter/tool/builder.go
Working with multiple layers, snapshotter produces trivial logs.
=> feat: Only retain serious log while unpacking

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, config/daemonconfig.go, pkg/cache/manager.go, pkg/daemon/config.go, pkg/daemon/daemon.go, pkg/filesystem/fs/config.go, pkg/filesystem/fs/fs.go, pkg/process/manager.go, snapshot/snapshot.go
fs-driver is a more descriptive name since fusedev and
fscache/cachefiles is a file system driver. In fact, fusedev
is nydusd's front-end. This patch also marks --daemon-backend
as deprecated.
=> common: add flag --fs-driver to replace --daemon-backend

.github/workflows/ci.yml
In case the latest nydus release breaks off the smoke test.
=> smoke: use latest nydus release

MAINTAINERS
Yan Song @imeoer  is a core developer and maintainer of Nydus container image service, especially on the `nydusd` runtime/filesystem and building nydus container image via `nydus-image`, `nydusify` and [Harbor Accelleratioin Service](https://github.com/goharbor/acceleration-service) sub-project. For nydus-snapshotter he had completed features like the setting up nydus snapshots using Erofs/Fscache fs driver, which directly works on top of Linux in-kernel filesystem as container rootfs with lazyload capability, an essential feature in the upcoming nydus release. In addition, he contributed to the feature that nydus-snapshotter can directly use stargz container image to provide container rootfs with many other neat fixups.
He is eager to help community users with rich experience.
I'd like …
=> MAINTAINERS: Add Yan Song as a reviewer

pkg/daemon/daemon.go, pkg/filesystem/fs/fs.go, snapshot/snapshot.go
Optimize snapshotter to reduce container startup time by
1) avoid probing stargz layer for nydus metadata layer.
2) start shared nydusd daemon early, so it doesn't penalize the first container.
=> Optimize snapshotter to reduce container startup time

pkg/cache/store.go
Remove blob.meta files when deleting nydus blob files.
Fixes: https://github.com/containerd/nydus-snapshotter/issues/110
Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>
=> Remove blob.meta files when GC nydus blob files

misc/snapshotter/nydus-snapshotter.fscache.service, misc/snapshotter/nydus-snapshotter.fusedev.service
Otherwise, systemd will send SIGTERM to nydusd forked by
nydus-snapshotter ending up with nydusd exit and fuse session
disconnected.
=> change systemd KillMode to process

pkg/process/manager.go
`fuse` subcommand is not compatible with old nydusd.
So remove it and new nydusd can use fuse as default mode.
=> remove nydusd daemon mode fuse when starting

go.mod, go.sum, pkg/filesystem/fs/fs.go
Optimize handling of stargz images by:
1) use reflink copy when possible to copy blob.meta files.
2) avoid merging stargz layers when there's only one layer.
=> Optimize handling of stargz images

pkg/process/manager.go
Reverts containerd/nydus-snapshotter#119
`fuse' shouldn't be the default mode. It makes no sense to submit such commit.
=> Revert "remove nydusd daemon mode fuse when starting"

misc/snapshotter/nydusd-config.fusedev.json
Change typical prefetch threads to 8 and merging size to 1048576
=> typical nydusd/rafs configuration file

misc/snapshotter/nydus-snapshotter.fscache.service, misc/snapshotter/nydus-snapshotter.fusedev.service, pkg/process/manager.go
If nydusd does not make to reach logging setup when starting, it can not log any errors to its logger.
At present, nydusd's stderr is only redirected to snapshotter with `--log-to-stdout` enabled. But the option 
should only control nydusd's logs rather than its stderr and stdout.
This helps us with analyzing  failed started container
=> enhance how nydusd's log are logged and redirected

tests/converter_test.go
Throws a panic like below when run TestUnpack test case:
```
converter_test.go:415:
Error Trace:	converter_test.go:415
Error:      	Not equal:
expected: "sha256:b4679f7afa21a5513d84ba7d9a6faf2621f101421c830648512cd63475118fa1"
actual  : "sha256:92ad2fb1075eabd299daa2dbb5e822031c198551fa9cebf29046ed79efa27ce3"
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-(digest.Digest) (len=71) "sha256:b4679f7afa21a5513d84ba7d9a6faf2621f101421c830648512cd63475118fa1"
+(digest.Digest) (len=71) "sha256:92ad2fb1075eabd299daa2dbb5e822031c198551fa9cebf29046ed79efa27ce3"
Test:       	TestUnpack
```
Related: https://github.com/dragonflyoss/image-service/pull/630
To make the unpacked tar consistent with the OCI-formatted tar before the pack,
we need to backfill the username and groupname in the tar header, …
=> tests: fix panic for unpack test

.github/workflows/image.yml, misc/snapshotter/Dockerfile, misc/snapshotter/nydusd-config-localfs.json, pkg/filesystem/fs/fs.go, snapshot/snapshot.go
Previously in the localfs backend mode, when blobMgr delete the blob
corresponding to the snapshot, it mistakenly used the key (chainID)
issued by containerd as the blob digest, resulting in only the first
layer of blob being deleted.
Now
1. For the scenario of converting OCI to Nydus image, get the blob
digest, in fact the snapshot key by label NydusDataLayer, the kv pair
(NydusDataLayer --> snapshot key) has been set after the convert.
2. For the scenario of full download of nydus image, get the correct
blob digest by label CRILayerDigest.
=> Fix BlobMgr Remove

pkg/filesystem/fs/fs.go, snapshot/snapshot.go
Previously, both AddSnapshot and DelSnapshot will not be executed in
the none daemon mode. The fundamental reason is that the incoming
parameter is the imageID obtained from the daemon. Now we adjust the
function call path to bypass the daemon and get the imageID directly
from snapshot labels.
For AddSnapshot, we separate it from prepareRemoteSnapshot, run it
separately, and parse the imageID directly from the snapshot label.
For DelSnapshot, we advance it from Cleanup to Remove.
=> cache manager: fix cache manager failure in none daemon mode

cmd/containerd-nydus-grpc/app/snapshotter/main.go, cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, pkg/auth/keychain.go
If node has no kubelet deployed, listener will report warning forver:
E0815 10:37:46.330502 1446182 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.5/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: Get "https://127.0.0.1:27949/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fdockerconfigjson&limit=500&resourceVersion=0": dial tcp 127.0.0.1:27949: connect: connection refused
E0815 10:38:30.398522 1446182 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.5/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: Get "https://127.0.0.1:27949/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fdockerconfigjson&limit=500&resourceVersion=0": dial tcp 127.0.0.1:27949: connect: connection refused
E0815 10:39:08.890713 1446182 …
=> add a flag to control whether enable kubeconfig keychain

pkg/daemon/config.go, pkg/daemon/daemon.go, pkg/filesystem/fs/fs.go, snapshot/snapshot.go
1. Erofs/fscache can't work in ordinary SharedMount mode since each erofs has a seperated mountpoint while shareMode means one nydusd one mountpoint.
2. rafs as lowerdir and read-only underlying FS should be mounted at `/mnt`. `fs` is used to store bootstrap for meta layer and writeable for Active snapshot
3. `fs` has permission 0700, which causes other user in the container can't read /bin dir
=> clean up and fix how nydus-snapshotter prepares mountpoints for nydusd

go.mod, go.sum, pkg/daemon/idgen.go
The original ID generation method spawns a string with
lower case, upper case and undersocre, which is too complicated.
=> use xid to generate nydusd's internal ID

snapshot/snapshot.go
The user of ctr/nerdctl may be different from the user of nydus snapshotter.
In order to allow users of ctr and nerdctl to access rootfs, other group permissions need to be given here,
and the default permission of overlayfs is also 0755
Signed-off-by: zyfjeff <zyfjeff@linux.alibaba-inc.com>
=> Change upperPath permission from 0750 to 0755

Makefile
When building on arm64 machine, don't build amd64 as default GOARCH.
=> Make current machine's arch as defaulted GOARCH

cmd/containerd-nydus-grpc/main.go, pkg/daemon/daemon.go, pkg/process/manager.go
Nydusd judges if it should enter failover phrase by
checking residual disconnected unix socket file and mounted
mountpoint. But if snapshotter is restarting, nydusd can't fetch
back its states. So just start a fresh nydusd
=> clean up nydus vestige when starting

misc/snapshotter/nydusd-config.fscache.json
So nydusd in fscache mode can have a better porformance.
=> configure prefetch in example fscache nydusd config file

pkg/filesystem/fs/resolver.go
When the single-layer image is too large or the network bandwidth is poor, it is easy to reach this timeout period. The default resolver of docker has no timeout limit, so this timeout limit is removed here, and the timeout is controlled by upper-layer tools such as nerdctl/ctr/crictl.
Signed-off-by: zyfjeff <zyfjeff@linux.alibaba-inc.com>
=> Remove default http timeout limit

integration/entrypoint.sh, pkg/daemon/daemon.go, pkg/errdefs/errors.go, pkg/filesystem/fs/fs.go, pkg/process/manager.go, pkg/process/store.go, pkg/store/daemonstore.go, snapshot/snapshot.go
Several community users and nydus contributors have complained about nydus-snapshotter's usability and stability.
1. nydusd is not ready so the container image can't be accessed
2. nydus image can't be accessed after rebooting the host
To solve the issues once and for all, this PR refactors nydusd daemons states management. It decouples in-memory states cache from DB persistence storage. Snapshotter never empties the DB when restarting but to rebuild the in-memory daemon states cache to get consistent with DB persistent storage. In addition, it will request API to restarted nydusd daemon to recover the API mounts.
Several E2E cases are accompanied.
Address: https://github.com/containerd/nydus-snapshotter/issues/142 https://github.com/containerd/nydus-snapshotter/issues/125
=> Enhance daemon states management to improve usability and stability

config/daemonconfig.go, pkg/auth/docker_test.go, pkg/converter/convert_unix.go, pkg/filesystem/fs/fs.go, pkg/filesystem/fs/stargz/resolver.go, pkg/filesystem/fs/stargz/resolver_test.go, pkg/nydussdk/client.go, pkg/signature/signature.go, pkg/utils/transport/pool.go, snapshot/snapshot.go, tests/converter_test.go, tests/nydusd.go
golangci-lint run
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. pkg/signature/signature.go:12:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
"io/ioutil"
^
pkg/filesystem/fs/fs.go:15:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those …
=> replace deprecated ioutil package

integration/entrypoint.sh
e2e test already builds nydus-snapshotter with `-race` flag. Now let's add a checkpoint for go race detection.
=> detect go race condition when perform e2e test

snapshot/snapshot.go
In some cases, such as a user-defined label in the upper layer, the snapshot label is not empty, but does not contain
"containerd.io/snapshot/cri.image-ref", the function should continue to execute normally instead of returning an error.
=> [Bugfix] Modify the logic of obtaining image ref when deleting snapshots

pkg/process/manager.go
We've renamed `daemon` subcommand to `singleton`.
Ref: https://github.com/dragonflyoss/image-service/pull/722
Please only merge this when upgrading nydusd dependency version.
=> manager: update nydusd commandline options

pkg/converter/convert_unix.go, pkg/converter/tool/builder.go, tests/converter_test.go
Affected by chunk dict, the blob list referenced by final bootstrap
are from different layers, part of them are from original layers,
part from chunk dict bootstrap.
So we need to rewrite manifest's layers using the real blob list
referenced by final bootstrap.
=> converter: fix incorrect blob list from merge

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, integration/Dockerfile, integration/entrypoint.sh, misc/snapshotter/nydus-snapshotter.fusedev.service, pkg/daemon/daemon.go, pkg/nydussdk/client.go, pkg/process/manager.go, pkg/process/monitor_linux.go, pkg/process/monitor_other.go, pkg/process/monitor_test.go, pkg/process/states_cache_test.go, pkg/process/store.go, pkg/store/daemonstore.go, snapshot/snapshot.go
At present, nydus-snapshotter is not aware of the termination of nydusd. When a nydusd is dead somehow, snapshotter can't clean up its vestige and reclaim its resources. By introducing the daemon's liveness monitor, the snapshotter can restart nydusd when the old one dies.
=> Introduce daemons liveness monitor

config/daemonconfig.go, pkg/filesystem/fs/config.go
Nydusd is going to support adding multiple registry mirrors as a pull-through cache.
So snapshotter should also load mirror-related configuration items and provide them to nydusd.
relates to https://github.com/dragonflyoss/image-service/pull/736
=> support configure nydusd mirror registry

cmd/containerd-nydus-grpc/pkg/command/flags.go, misc/snapshotter/nydus-snapshotter.fusedev.service
In addition remove --recover-plicy from systemd service file since restart is default one now.
=> fix wrong description in help message

pkg/filesystem/fs/fs.go, snapshot/snapshot.go
The ctx is only used to print log.
Let's use log.L instead
=> remove ctx from snapshotter object

pkg/daemon/daemon.go, pkg/nydussdk/client.go, pkg/process/monitor_linux.go, pkg/utils/retry/retry.go, snapshot/snapshot.go
Backendoff delay policy brings longer and longer
delay when retrying. So it brings long latency to
set up images snapshots when creating containers.
=> turn delay policy from Backoff to Fixed

config/daemonconfig.go
Mirror host should be filled with URL rather than URI
=> remove scheme from mirro configuration

pkg/process/manager.go
If any step fails after deleting daemon from DB, it won't cause daemon record residual.
Residual daemon records will cause snapshotter restart the nydusd continuously.
=> delete daemon from DB in the first place when removing snapshot

integration/entrypoint.sh, pkg/daemon/daemon.go, pkg/filesystem/fs/fs.go
Nydusd daemon record can be wrongly deleted from DB when nydusd fails to start up. A reliable and stable way to fix is to refactor nydusd daemon and rafs instance relationship. So the workaround is just start a new daemon when it can't be found from states cache and DB.
In addition, we should reset client when clear daemons vestige since the API socket has to be re-created by the new nydusd
=> Fix daemon race

pkg/daemon/daemon.go
otherwise, go race happens:
go race detected
2022-09-28T03:58:01.2478136Z ==================
2022-09-28T03:58:01.2478813Z WARNING: DATA RACE
2022-09-28T03:58:01.2479296Z Write at 0x00c00017a8d0 by goroutine 40:
2022-09-28T03:58:01.2480254Z   github.com/containerd/nydus-snapshotter/pkg/daemon.(*Daemon).ResetClient()
2022-09-28T03:58:01.2618661Z       /home/runner/work/nydus-snapshotter/nydus-snapshotter/pkg/daemon/daemon.go:286 +0x4b9
2022-09-28T03:58:01.2619768Z   github.com/containerd/nydus-snapshotter/pkg/daemon.(*Daemon).ClearVestige()
2022-09-28T03:58:01.2620682Z       /home/runner/work/nydus-snapshotter/nydus-snapshotter/pkg/daemon/daemon.go:367 +0x4a5
2022-09-28T03:58:01.2621606Z   github.com/containerd/nydus-snapshotter/pkg/process.(*Manager).handleDaemonDeathEvent.func1() …
=> fix go race when resetting http client

pkg/process/manager.go
Otherwise, it skips checking nydusd's socket's existence.
=> reset virtual daemon's nydusd client

pkg/process/manager.go, snapshot/snapshot.go
This is very helpful when debug and trace how
nydus-snapshotter is releasing resources.
=> print which directories are being deleted

go.mod, pkg/daemon/command/command.go, pkg/daemon/command/command_builder_test.go, pkg/daemon/config.go, pkg/daemon/daemon.go, pkg/process/daemon_adaptor.go, pkg/process/manager.go
Generate nydusd exec style command line via a daemonCommand object. It provides the flexibility to start nydusd as a library API. 
Move nydusd daemon startup logics to a new file `daemon_adapter.go`
=> Add nydusd daemon command line builder

pkg/daemon/client.go, pkg/daemon/client_test.go, pkg/daemon/command/command_builder_test.go, pkg/daemon/daemon.go, pkg/filesystem/fs/config.go, pkg/filesystem/fs/fs.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/monitor_linux.go, pkg/manager/monitor_other.go, pkg/manager/monitor_test.go, pkg/manager/states_cache_test.go, pkg/manager/store.go, pkg/metric/serve.go, pkg/process/daemon_adaptor.go, pkg/process/manager.go, snapshot/snapshot.go
We aim to put all logic that starts nydusd, queries nydusd, and controls nydusd to the daemon package.
So the daemons manager as well as other projects like KataContainers can easily call daemon functions to operate nydusd daemons/
This RR contains no logical changes.
=> Move nydusd http client code to daemon package

config/daemonconfig.go, pkg/utils/erofs/erofs_linux.go, pkg/utils/erofs/erofs_other.go
https://lore.kernel.org/linux-erofs/20220902105305.79687-1-zhujia.zj@bytedance.com/T/#t
Signed-off-by: Jia Zhu <zhujia.zj@bytedance.com>
=> Support shared domain

pkg/daemon/daemon.go
They are used by failover and live-upgrade framework
=> public three nydusd API through daemon methods

config/daemonconfig.go
Nydusd needs a parameters to determine if it is authorized through mirror. 
So snapshotter should also load auth_through item and provide it to nydusd.
=> support configure authorization through mirror

pkg/daemon/daemon.go
There is a race between reseting client during recovering daemons and requesting to daemon.
=> lock daemon client when requesting to daemon

.github/workflows/release.yml
The release action can't upload artifacts when it told the error:
🤔 Pattern 'nydus-snapshotter-v0.11.2-x86_64.tgz nydus-snapshotter-v0.11.2-x86_64.tgz.sha256sum' does not match any files. 👩‍🏭 Creating new GitHub release for tag v0.11.2... 🤔 nydus-snapshotter-v0.11.2-x86_64.tgz nydus-snapshotter-v0.11.2-x86_64.tgz.sha256sum not include valid file. 🎉 Release ready at https://github.com/containerd/nydus-snapshotter/releases/tag/v0.11.2
So we shoud use literal style yaml block to keep the newline untouched
=> fix broken release github action

pkg/converter/convert_unix.go
This pr fixes the fs-version annotation error of the converted Nydus bootstrap layer.
By now, the "containerd.io/snapshot/nydus-fs-version" annotation of the converted bootstrap layer is always `5` which is the default value. The reason for this error is that the value of `MergeOption.FsVersion` is not assigned correctly in the `convertManifest` function of `convert_unix.go` when call the `MergeLayers` function and the `MergeLayers` always uses the empty string as the value of `MergeOption.FsVersion`.
Signed-off-by: Nan Li <loheagn@icloud.com>
=> Fix the annotation error of the converted bootstrap layer

integration/entrypoint.sh, pkg/cache/manager.go, pkg/daemon/client.go, pkg/daemon/daemon.go, pkg/daemon/types/types.go, pkg/filesystem/fs/fs.go, snapshot/snapshot.go
Report nydusd blob cache real disk usage. We can find blob layer digest from labels thus to locate the blob cache file rather than use the fake usage in DB. This can benefit Kubelet imagefs based Pod eviction.
```
KEY                                                                     SIZE      INODES
109b7d58b01ebec145bb9442e4ccc689924cc0ff58a1cfec4e9c2e4dd8b42406        1.2 GiB   83
1ec71efdd3b1e343aadba2cb99799cd449f6265c586b676d187ebd6fa5da365a        1.2 GiB   87
connectiontest-dummy-MWJlMjQwOT                                         1.2 GiB   83
sha256:02b8d8942291bd3719dc67b9a13c546b35dcbd997abbdc8895f46a04b1e955b0 4.0 KiB   1
sha256:14378bfef64c87c460841af12e60e2322a37242bda61d315dc5042eb2cc4d9cc 4.0 KiB   1
sha256:2b9b33469ea282b43c5a86ee628ba968f6ada2f1979e1863077ec209f63fb469 …
```
=> Report nydus real blob cache disk usage

config/daemonconfig.go
The failure_limit indicates the failed time at which the mirror is set to unavailable, and the health_check_interval indicates the time interval to recover the unavailable mirror.
This PR is related to https://github.com/dragonflyoss/image-service/pull/800
=> support configure nydusd mirror health checking

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/release.yml
Update actions/checkout, actions/cache, and actions/upload-artifact to v3.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Related issue: https://github.com/containerd/project/issues/95
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Update GitHub actions packages in workflows

.github/workflows/ci.yml, .golangci.yml
Updates golangci-lint to v1.50.1 and removes a duplicate linter setting.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Update golangci-lint to v1.50.1

pkg/daemon/daemon.go, pkg/daemon/types/types.go, pkg/manager/manager.go
At present, nydus-snapshotter queries daemon's state each
time when it gets daemon object's state. The query comes
from several positions which cause duplicated query.
We can use single-flight mechanism to query daemon'state
to reduce unnecessary comunications between processes.
This changeset will benefit container startup performance.
=> Running state cache

cmd/containerd-nydus-grpc/main.go, config/config.go, pkg/filesystem/fs/config.go, pkg/filesystem/fs/fs.go, pkg/manager/manager.go, snapshot/snapshot.go
I have observed that users misuses snapshotter's fsdirver parameter by changing it between two startups. As the daemon is
persisted to database, snapshotter can't at the same time serves two types of fsdrvier. So we should abort this startup
Otherwise, even snapshotter can restore and recover daemons during this startup, it can't provide correct rootfs.
=> fails snapshotter startup if its fsdriver mismatches daemon's

config/daemonconfig/fscache.go
The prefetch config part is lacked in fscache configuration
=> pass prefetch config to fscache config

.github/workflows/ci.yml, .github/workflows/e2e.yml
Follow-up for https://github.com/containerd/nydus-snapshotter/pull/241
Resolves GitHub actions CI/Integration test workflow warnings for NodeJS 12 actions, `set-output` and `save-state` command usage by upgrading codecov/codecov-action and docker/login-action packages.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
CI run pre-changes: https://github.com/containerd/nydus-snapshotter/actions/runs/3510786084
Integration test run pre-changes: https://github.com/containerd/nydus-snapshotter/actions/runs/3510786085
Related-issue: https://github.com/containerd/project/issues/95
Signed-off-by: Austin Vazquez …
=> Resolve GitHub actions workflow warnings

pkg/daemon/daemon.go, pkg/manager/manager.go
A new nydusd has to be brought up, so we have
to query the daemon state again.
=> clear daemon state after nydusd dies

cmd/containerd-nydus-grpc/pkg/command/flags_test.go, cmd/containerd-nydus-grpc/pkg/logging/setup_test.go, pkg/backend/oss.go, pkg/blob/blob_manager.go, pkg/blob/blob_manager_test.go, pkg/daemon/client.go, pkg/daemon/client_test.go, pkg/daemon/command/command_builder_test.go, pkg/daemon/daemon.go, pkg/filesystem/fs/fs.go, pkg/filesystem/fs/stargz_adaptor.go, pkg/manager/monitor.go, pkg/manager/monitor_test.go, pkg/metrics/ttl/gauge_test.go, pkg/snapshot/storage.go, pkg/stargz/resolver.go, pkg/store/database.go, pkg/store/database_compat.go, pkg/store/database_test.go, pkg/supervisor/supervisor.go, pkg/utils/signals/signal_test.go, snapshot/snapshot.go, tests/converter_test.go, tests/nydusd.go
1. Reduce unnecessary database queries
2. enable `errcheck` linter
This PR is very likely to reduce snapshot setup latency.
=> Optimize how nydus meta snapshot is prepared and enable errcheck linter

pkg/daemon/client.go, pkg/daemon/daemon.go, pkg/daemon/rafs.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/system/system.go, pkg/system/system_test.go
Add a control flow of nydusd live-upgrade to the system package.
=> Add nydusd live-upgrade control flow

pkg/manager/manager.go
Rafs is already mounted during starting nydusd.
=> don't invoke API to mount rafs if it is not shareDaemon

Makefile, pkg/converter/convert_unix.go, tests/converter_test.go, tests/nydusd.go
Unpacking file from nydus blob should seek until encountering the head
of blob stream, this patch ensures this to improve unpack compatibility
and refine the test codes.
=> converter: enhance nydus tar unpack

pkg/daemon/daemon.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go
It is possible that snapshotter waits for RUNNING
state before waits for INIT stat which is a deadlock
=> get rid of getting daemon state in single flight

.github/workflows/release.yml
Updates actions/checkout and actions/download-artifact packages from v2 to v3 to resolve NodeJS 12 warnings.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Related issue: https://github.com/containerd/project/issues/95
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Resolve warnings in GitHub actions release workflow

config/daemonconfig/fuse.go
Fix the issue#271 , just add the two fileds to the nudusd config,local test the containerd-nydus-grpc works well.
Also, this is my first PR, so I am not sure the work is right, It look like so simple, but I can't find any other correlation that needs to be modified.
=> feat: add some nydusd-config for metrics work

cmd/containerd-nydus-grpc/app/snapshotter/testdata/happypath/config.json, config/daemonconfig/daemonconfig_test.go, misc/snapshotter/nydusd-config.fscache.json, misc/snapshotter/nydusd-config.fusedev.json, pkg/stargz/testdata/config/nydus.json
remove scheme field in nydusd config
We have implemented automatically scheme detect for nydusd in this PR:
https://github.com/dragonflyoss/image-service/pull/893#merged-event
So we can remove the default scheme field in nydusd config file.
=> remove scheme field in nydusd config

go.mod
v0.3.0 was retagged: https://github.com/containerd/nydus-snapshotter/compare/cd604c1b597558ea045a79c4f80a8c780909801b...85653575c7dafb6b06548478ee1dc61ac5905d00
https://github.com/containerd/nerdctl/issues/1627#issuecomment-1343751786
Description about the `retract` directive: https://go.dev/ref/mod#go-mod-file-retract
=> go.mod: retract v0.3.0

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, snapshot/snapshot.go
We should put all snapshotter's stuff under root dir which can be customized.
=> maintenance api server's default socket should be under root dir

Makefile, README.md, config/config.go, integration/entrypoint.sh, misc/snapshotter/nydus-snapshotter.fscache.service, misc/snapshotter/nydus-snapshotter.fusedev.service
1. --config-path "/etc/nydus/nydusd-config.fusedev.json" or
"/etc/nydus/nydusd-config.fscache.json"
2. Add a symlink /etc/nysud/nydusd-config.json to match the default configuration.
In order to match
https://github.com/dragonflyoss/image-service/pull/955
Signed-off-by: Gao Xiang \<hsiangkao@linux.alibaba.com\>
=> treewide: tidy up --config-path

pkg/daemon/daemon.go, pkg/manager/daemon_adaptor.go, pkg/metrics/collector/collector.go, pkg/metrics/collector/snapshotter.go, pkg/metrics/data/snapshotter.go, pkg/metrics/tool/common.go, pkg/metrics/tool/stat.go, pkg/system/system.go
Collect some metrics about nydusd system resource consumption during its startup procedure. 
It will be helpful when analyze application startup latency
=> Collect nydusd startup cpu utilization and report its mem usage

Makefile
ln: failed to create symbolic link '/etc/nydus/nydusd-config.json': File exists
It's more convenient and does not disturb users
=> ignore existing symlink target existence

pkg/daemon/client.go, pkg/daemon/daemon.go, pkg/daemon/rafs.go, pkg/filesystem/fs.go, snapshot/snapshot.go
=> Fscache gc

pkg/store/database_compat.go
For shared daemon mode, it has diffent location to store those configurations
=> redirect nydusd and rafs instance configuration to new location

README.md, docs/run_nydus_in_kubernetes.md
This new document will describe how to create a local Kubernetes cluster using kind and then deploy nydus snapshotter in the Kubernetes cluster.
=> docs: add docs for running nydus snapshotter in Kubernetes

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, pkg/metrics/listener.go, pkg/metrics/serve.go, pkg/system/system.go, snapshot/snapshot.go
The common way to display prometheus format data is through the HTTP server. For instance, [Grafana](https://grafana.com/grafana) does not support collecting metrics from `unix domain socket`. Therefore, we should change the `unix domain socket` server to a HTTP server.
Here is an example:
```shell
containerd-nydus-grpc --config-path /etc/nydus/config.json -metrics-address :9010 --log-to-stdout
curl http://localhost:9010/metrics
```
Then, you will see the prometheus metrics.
=> metrics: support HTTP metrics server

config/daemonconfig/fuse.go
This is an experimental feature. With the warmup option, the nydus daemon could cache more data on the local disk to increase hit ratio.
=> config: add warmup option for nydus daemon

README.md, docs/configure_nydus.md
Add RBAC/ServiceAccount configs for kubeconfig keychain, and add an example of creating a secret of dockerconfig.
=> docs: add more details about how to use kubeconfig keychain

pkg/daemon/daemon.go, pkg/daemon/types/types.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/metrics/collector/collector.go, pkg/metrics/collector/daemon.go, pkg/metrics/collector/fs.go, pkg/metrics/data/daemon.go, pkg/metrics/data/fs.go, pkg/metrics/registry/registry.go
Add nydus daemon version to prometheus format metrics.
```=
nydusd_version_string{version="v2.1.0-rc.3.1-473-gf4dd9e1c"} 1
```
Moreover, remove some metrics that have been deleted in nydus and improve descriptions for daemon FS metrics.
=> metrics: add nydus daemon version

pkg/metrics/collector/collector.go, pkg/metrics/collector/fs.go, pkg/metrics/data/fs.go, pkg/metrics/registry/registry.go, pkg/metrics/serve.go, pkg/metrics/types/types.go
Improve FS metrics to collect histograms with labels. Moreover, remove unused metric OpenFdCount.
=> metrics: improve FS metrics and remove unused metrics

Makefile, integration/entrypoint.sh
So developers can replace the images' sources to boost test procedure
=> e2e: provide a makefile parameters thus to replace test target images

misc/snapshotter/Dockerfile
The github workflow frequently causes errors to break tests:
```
Step 4/18 : RUN export NYDUS_VERSION=$(curl --silent "https://api.github.com/repos/dragonflyoss/image-service/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")') &&     wget https://github.com/dragonflyoss/image-service/releases/download/$NYDUS_VERSION/nydus-static-$NYDUS_VERSION-linux-amd64.tgz &&     echo $NYDUS_VERSION > /.nydus_version &&     tar xzf nydus-static-$NYDUS_VERSION-linux-amd64.tgz &&     rm nydus-static-$NYDUS_VERSION-linux-amd64.tgz
---> Running in 39df2748e06d
Connecting to github.com (140.82.112.4:443)
wget: server returned error: HTTP/1.1 404 Not Found
The command '/bin/sh -c export NYDUS_VERSION=$(curl --silent "https://api.github.com/repos/dragonflyoss/image-service/releases/latest" | grep -Po …
```
=> misc: fix 404 for snapshotter dockerfile

cmd/containerd-nydus-grpc/app/snapshotter/snapshotter.go, cmd/containerd-nydus-grpc/main.go, cmd/containerd-nydus-grpc/pkg/command/flags.go, cmd/containerd-nydus-grpc/pkg/logging/setup.go, config/config.go, config/config_test.go, config/default.go, config/global.go, export/snapshotter/snapshotter.go, misc/snapshotter/config.toml, pkg/daemon/rafs.go, pkg/filesystem/fs.go, pkg/filesystem/stargz_adaptor.go, pkg/system/system.go, snapshot/snapshot.go
Introduce nydus-snapshotter's own TOML based configuration file.
At present, nydus-snapshotter can only be configured by command line parameters which have a large number. Moreover, those parameters tend to expand in the future as more and more features are developed.
Current command line parameters still have a high priority and override the items in the configuration file. We are planning to remove the command line parameters in the future.
Addresses  https://github.com/containerd/nydus-snapshotter/issues/215
=> nydus-snapshotter own configuration file

pkg/daemon/client.go, pkg/daemon/daemon.go, pkg/daemon/types/types.go, pkg/metrics/collector/collector.go, pkg/metrics/collector/fs.go, pkg/metrics/data/fs.go, pkg/metrics/registry/registry.go, pkg/metrics/serve.go
Add the metric TotalHangIO to record the total hang IO counts of FS. The inflight IOs data are from nydus daemon API `/api/v1/metrics/inflight`.
Output:
```
nydusd_hang_IO_counts{opcode="OP_READ"} 2
```
=> metrics: add metrics for FS hang IOs

pkg/metrics/serve.go
The metrics for `/api/v1/metrics` are in the RAFS of nydus daemon. When the driver is fscache, there are no metrics in RAFS.
=> metrics: avoid collect FS metrics for fscache driver

pkg/metrics/serve.go
Similar to FS metrics. The metrics for /api/v1/metrics/inflight are in the RAFS of nydus daemon.
When the driver is fscache, there are no metrics in RAFS.
=> metrics: avoid to collect inflight metrics for fscache driver

integration/Dockerfile
It's time to update nydusd dependency to v2.1.2
=> update e2e test nydusd deps

cmd/containerd-nydus-grpc/main.go, cmd/containerd-nydus-grpc/pkg/command/flags.go, cmd/containerd-nydus-grpc/pkg/logging/setup.go, cmd/containerd-nydus-grpc/pkg/logging/setup_test.go, config/config.go, misc/snapshotter/entrypoint.sh
Nydus-snapshotter now has its own toml based configuration file whose entries are duplicated with CLI startup parameters.
In the first phase, we will remove those not frequently used cli parameters and suggest users to migrate the configuration to toml based configuration file.
=> Remove some cli parameters

misc/snapshotter/entrypoint.sh, tests/e2e/k8s/snapshotter-cri.yaml, tests/e2e/k8s/snapshotter-kubeconf.yaml
Fix the nydus-snapshotter CLI parameters in k8s e2e test docker file where several CLI parameters are removed
=> fix k8s e2e test docker file

pkg/manager/manager.go
go race detected
WARNING: DATA RACE
Read at 0x00c0000bed48 by goroutine 34:
github.com/containerd/nydus-snapshotter/pkg/metrics/collector.(*DaemonInfoCollector).Collect()
/home/runner/work/nydus-snapshotter/nydus-snapshotter/pkg/metrics/collector/daemon.go:33 +0x78
github.com/containerd/nydus-snapshotter/pkg/manager.(*Manager).handleDaemonDeathEvent()
/home/runner/work/nydus-snapshotter/nydus-snapshotter/pkg/manager/manager.go:314 +0x212
github.com/containerd/nydus-snapshotter/pkg/manager.NewManager.func1()
/home/runner/work/nydus-snapshotter/nydus-snapshotter/pkg/manager/manager.go:364 +0x39
Previous write at 0x00c0000bed48 by goroutine 88:
github.com/containerd/nydus-snapshotter/pkg/manager.(*Manager).StartDaemon.func2()
/home/runner/work/nydus-snapshotter/nydus-snapshotter/pkg/manager/d …
=> fix a gorace when retrieving Version from daemon object

config/default.go
As other default value may depend on root dir.
=> assign root dir in the first place when filling up defaults

MAINTAINERS
Yan Song @imeoer has worked for nydus-snapshotter reviewer for half a year and is eager to review many PRs and gave a number of remarkable PR comments, which is a great promotion for the project. He also contributed many patches and features to the nydus-snapshotter project, especially in the field of nydus container image build which has already been integrated into `nerdctl` and `Buildkit`, and proposed some meaningful ideas to help the project grow.
I'd like to invite him as a nydus-snapshotter committer if he would approve :)
Needs explicit LGTM from @imeoer and 1/3 of the nydus-snapshotter committers:
=> Invite Yan Song as nydus-snapshotter committer

pkg/daemon/daemon.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/monitor.go, pkg/metrics/collector/collector.go, pkg/metrics/collector/daemon.go
There is a race that multiple goroutines can call WaitUntilState() at the same time and waiting for the same expected state. So they can both escape from the very beginning state check ending up with an extra event record.
=> fix that nydusd lifecycle event might be duplicated

pkg/daemon/daemon.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/monitor.go, pkg/metrics/collector/collector.go, pkg/metrics/collector/daemon.go
Clearly pick some stable patches for v0.5 and prepare to release v0.5.1
=> Back port some stable patches for v0.5.x

cmd/containerd-nydus-grpc/main.go, cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, misc/snapshotter/config.toml, tests/e2e/k8s/containerd.config.toml, tests/e2e/k8s/snapshotter-cri.yaml, tests/e2e/k8s/snapshotter-kubeconf.yaml
In this phase, we are going to remove K8s auth passing related parameters and suggest users to migrate to nydus-snapshotter's toml configuration file to achieve it
=> Remove CLI K8s auth passing related parameters 

config/config.go, config/config_test.go, go.mod, misc/snapshotter/config.toml, snapshot/snapshot.go
We are pursuing a more fine-grained configuration section for metrcis, e.g. scrape interval, etc
=> move metrics config to a separated section

cmd/containerd-nydus-grpc/pkg/command/flags.go, cmd/containerd-nydus-grpc/pkg/command/flags_test.go, config/config.go, config/default.go, integration/Dockerfile, integration/entrypoint.sh, misc/snapshotter/config.toml, pkg/manager/manager.go, snapshot/snapshot.go
In this stage, we're going the remove other not frequently used CLI parameters and let e2e test adapt it.
=> Remove the other cli parameters

config/config.go, config/global.go, misc/snapshotter/nydus-snapshotter.fscache.service
It will be more friendly to users by hiding some inner details
=> let fscache driver enforce shared daemon mode forcefully

README.md, docs/configure_nydus.md, misc/snapshotter/config.toml
Because some CLI parameters are removed, we have to arrange the docs
=> arrange docs after some cli parameters are deleted

Makefile, config/config.go, config/config_test.go, config/daemonconfig/daemonconfig.go, config/daemonconfig/fscache.go, config/daemonconfig/fuse.go, config/daemonconfig/mirrors.go, config/daemonconfig/mirrors_test.go, config/global.go, misc/snapshotter/config.toml, pkg/filesystem/fs.go
Now, the mirror registry is configured with nydusd config file. Reloading service is needed if we modify it after the nydus-snapshotter is run.
This commit solves this problem.
Snapshotter will overwrite the daemon's mirror configuration if the values loaded from this directory are not null before starting a daemon.
This PR is addressing #341 
=> config: support configuring mirror registry without reloading snapshotter

README.md
=> doc: add document about hot update mirror configurations

pkg/daemon/daemon.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go
=> update daemon version when getting state

config/config.go, config/config_test.go, config/default.go, config/global.go, misc/snapshotter/config.toml, pkg/manager/daemon_adaptor.go, pkg/system/system.go, snapshot/snapshot.go
1. move system controller config to a dedicated struct
2. capable of configuring daemon cpu profile duration
=> enable system controller config

config/config.go, config/config_test.go, misc/snapshotter/config.toml, snapshot/snapshot.go
As the stargz compatiblity feature is not production ready
and reliable enought
=> mark stargz configuration as experimental

README.md, docs/configure_nydus.md
=> add brief introduction on metrics and diagnose methods

docs/run_nydus_in_kubernetes.md, tests/e2e/k8s/containerd.config.toml
This PR migrate from `k8s.gcr.io` to `registry.k8s.io`
Part Of https://github.com/kubernetes/k8s.io/issues/4780
=> Migrate from k8s.gcr.io to registry.k8s.io

pkg/daemon/daemon.go
For fscache driver, the unique and shared  nydusd does not ever mount a filesystem on host. So we don't have to clean up
the mounts when deleting snapshots.
=> only do umount against nydusd that has host mounted

config/config_test.go, config/default.go, docs/configure_nydus.md, misc/snapshotter/config.toml
The default address should locate at
/var/run/containerd-nydus/system.sock
=> fix system controller default socket address

pkg/filesystem/fs.go
=> print the invalid blob digest to log

pkg/system/system.go
In order to print more info about image instance to help analyze
=> print instance image id from system diagnose API

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/k8s-e2e.yml, .github/workflows/release.yml, go.mod, integration/Dockerfile
Thus to catch up with containerd
=> upgrade project's golang version to 1.19.6

config/config.go, config/config_test.go, config/global.go, misc/snapshotter/config.toml, pkg/metrics/listener.go, pkg/pprof/listener.go, snapshot/snapshot.go
As titled. This PR is addressing #359
To visualise:
```shell
go tool pprof -http :LOCAL_PORT http://HOST:PORT/debug/pprof/goroutine
```
=> Add pprof HTTP server for snapshotter

pkg/metrics/collector/daemon.go, pkg/metrics/data/daemon.go, pkg/metrics/registry/registry.go, pkg/metrics/serve.go
Export nydus daemon memory usage (RSS) to prometheus metrics.
=> metrics: export nydus daemon memory usage (RSS)

pkg/metrics/listener.go, snapshot/snapshot.go
We should fail snapshotter's startup if the metrics address weren't bound.
=> fail the snapshotter immediately if metrics server can't be bound

snapshot/snapshot.go
Sandbox container image may not be downloaded through CRI flow. So  cri related annotations won't be appended.
=> only count nydusd local cache if it a nydus layer

pkg/system/system.go
Create the parent directory for the socket path if it does not exist.
=> system: fix no such file or directory error

cmd/containerd-nydus-grpc/pkg/command/flags.go, cmd/containerd-nydus-grpc/pkg/command/flags_test.go, config/config.go, config/config_test.go, misc/snapshotter/config.toml, tests/e2e/k8s/snapshotter-cri.yaml, tests/e2e/k8s/snapshotter-kubeconf.yaml
Remove default value of cmd arguments to avoid overwriting configuration loaded from `toml` file.
This PR is addressing #379
=> Fix the problem of snapshotter's toml configuration file not working

pkg/converter/convert_unix.go, pkg/converter/cs_proxy_unix.go, pkg/converter/tool/builder.go, pkg/converter/types.go, tests/converter_test.go
This patch adds stream mode to `Unpack`, which avoids to unpack the blob data to the local disk but sets up a local http server to proxy the blob data reading.
Signed-off-by: Nan Li <loheagn@icloud.com>
=> converter: add stream mode to `Unpack`

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, config/config_test.go, go.mod, go.sum, tests/e2e/k8s/snapshotter-cri.yaml, tests/e2e/k8s/snapshotter-kubeconf.yaml
Updates github.com/urfave/cli/v2 to v.2.24.4 which allows the usage of the `Count` property for `BoolFlag`. This enables the detection of the cmdline flag being set or not and allows for correctly overriding the option from the toml config.
The corresponding tests have been added as well.
Signed-off-by: Philipp Kolberg <philipp.kolberg@t-online.de>
=> Fix override for log-to-stdout cmdline option

pkg/daemon/client.go
Currently, snapshotter retries for 2s while waiting for the nydus daemon's unix domain socket file to exist. This probably causes the nydusd_count metric to be incorrect because it returns prematurely.
This PR is addressing #392
=> daemon: increase retry times to avoid premature returns

config/config.go, config/config_test.go, config/default.go, config/global.go
In the default configuration for snapshotter we fill the cacheDir and LogDir:
```go
logConfig := &c.LoggingConfig
if len(logConfig.LogDir) == 0 {
logConfig.LogDir = filepath.Join(c.Root, logging.DefaultLogDirName)
}
cacheConfig := &c.CacheManagerConfig
if len(cacheConfig.CacheDir) == 0 {
cacheConfig.CacheDir = filepath.Join(c.Root, "cache")
}
```
But we do not fill these elements after loading the configuration from the `toml' file and parsing the arguments. This results in cacheDir and LogDir not being in snapshotter's RootDir.
=> config: avoid to use default dir if root is valid

config/default.go
Nydusd and nydus-image's path be customized.
It should throw error if they can't be found.
=> allow nydusd and nydus-image absence in PATH

.golangci.yml, config/config_test.go, config/daemonconfig/mirrors_test.go, pkg/auth/image_proxy_test.go, pkg/auth/kubesecret.go, pkg/auth/kubesecret_test.go, pkg/backend/oss.go, pkg/converter/cs_proxy_unix.go, pkg/daemon/rafs.go, pkg/fanotify/fanotify.go
In addition, fix linter warnings reported by new linter.
=> enable more golang linters

config/daemonconfig/daemonconfig.go, config/daemonconfig/fscache.go, config/daemonconfig/fuse.go, config/daemonconfig/mirrors.go, config/daemonconfig/mirrors_test.go, pkg/filesystem/fs.go
Now, we load all the mirrorsConfig from directory. And the mirrorsConfig is available to all hosts. This is not compatible with containerd's mirror configuration. This PR tries to solve this issue.
=> daemonconfig: only load mirrorsConfig for target host

pkg/converter/convert_unix.go, pkg/converter/tool/builder.go, pkg/converter/types.go
Add `ParentBootstrapPath` option for `converter.Merge` method, the
option holds the bootstrap path of a parent image.
This option allows merging multiple bootstraps of upper layer with
the bootstrap of a parent image, so that we can implement container
commit operation for nydus image.
=> converter: support parent bootstrap for merge

cmd/containerd-nydus-grpc/main.go, config/config_test.go, config/global.go, pkg/utils/mount/mount.go
When the Root path is set as a relative path, Prepare return a relative path, the containerd will fail to mount.
=> fix containerd mount failed when root is a relative path

pkg/fanotify/conn/conn.go, pkg/fanotify/fanotify.go, tools/optimizer-server/Cargo.lock, tools/optimizer-server/Cargo.toml, tools/optimizer-server/src/main.rs
This PR tries to add more information to the optimizer. The file size and event timestamp are useful to understand the workload's IO pattern.
Related to #398
=> add size and timestamp for monitored files and dump to json file

pkg/fanotify/conn/conn.go
This PR tries to remove special token when reading stream from optimizer's stdout.
Related to https://github.com/containerd/nydus-snapshotter/pull/400
=> fanotify: decode json from reader to avoid specifying token

misc/snapshotter/entrypoint.sh
Fix the nydus snapshotter image not starting properly in v0.5.x because it would exit with wrong args in entrypoint.sh.
> $ sudo nerdctl run -d ghcr.io/containerd/nydus-snapshotter:v0.5.1
> 
> time="2023-03-16T03:29:02Z" level=fatal msg="failed to start nydus-snapshotter" error="flag provided but not defined: -enable-metrics"
=> [backport] remove not frequently used CLI parameters

docs/optimize_nydus_image.md, misc/snapshotter/Dockerfile
We should upgrade the version of nydus to v2.1.5 to fix known issues.
=> [backport] misc: update stable nydusd version v2.1.5 in Dockerfile and docs

docs/optimize_nydus_image.md, misc/snapshotter/Dockerfile
We should upgrade the version of nydus to v2.1.5 to fix known issues.
=> misc: update stable nydusd version v2.1.5 in Dockerfile and docs

pkg/fanotify/conn/conn.go, pkg/fanotify/fanotify.go, tools/optimizer-server/Cargo.lock, tools/optimizer-server/Cargo.toml, tools/optimizer-server/src/main.rs
We should always close event.fd even with error returned.
It's clear to show elapsed time than epoch time as the timestamp
Try to get rid of crate `chrono`, just use Rust std::time
=> fix bugs in image optimizer and improve the code a bit

config/config_test.go, config/daemonconfig/daemonconfig.go, config/default.go
So we can start nydus-snapshotter witout its toml config file with minimal parameters
=> set default value for fsdriver

pkg/filesystem/stargz_adaptor.go, pkg/stargz/resolver.go, snapshot/process.go, snapshot/snapshot.go, snapshot/utils.go
Right now, apart from making room for snapshot, snapshotter is also processing the blobs by converting or inspecting it. In the future, we may have more processing logic like them. So simplify and refactor related code for future work
=> Simplify the logics preparing snapshots for containerd

config/config_test.go, config/default.go, misc/snapshotter/config.toml
Otherwise, snapshotter will listen on a random unix socket
=> fill default snapshotter's address

pkg/converter/convert_unix.go
Associate a reference to the original OCI manifest, see the
`subject` field description in the doc:
https://github.com/opencontainers/image-spec/blob/main/manifest.md#image-manifest-property-descriptions
And if the converted manifest list contains only one manifest,
then convert it directly to manifest.
=> [stable/v0.7] converter: support OCI reference type

.github/workflows/optimizer.yml, go.mod, go.sum
1. upgrade runc to v1.1.5
2. upgrade protobuf to v1.30.0
=> deps: upgrade runc and protobuf to resolve vulnerabilities

README.md, docs/run_nydus_in_kubernetes.md
1. add link in docs/run_nydus_in_kubernetes.md and README.md
2. adjusted the article structure of README.md
=> docs: add helm quickstart link to deploy Dragonfly+Nydus

pkg/converter/utils.go
Reader.ReadAt() may return bytes read less than len(buf), so fix it.
=> converter: fix a possible bug in type seekReader::Read()

pkg/converter/tool/feature.go
Return null feature set for safety when failed to detect nydus-image version.
=> converter: return null feature set when failed to detect version

pkg/errdefs/errors.go, pkg/filesystem/fs.go, snapshot/process.go, snapshot/snapshot.go
Without inline layer fs meta blob, we can still support the topmost View for nydus image. It is useful for Buildkit to use nydus image as the base image.
Next PR will implement View on any layer of the nydus image.
```
➜  ~ ctr snapshot view --mounts cccddd sha256:62b1c52c224c7907ca34194f2c7e819b8057251b6d69623ff3bf8a7c9393894a
[
{
"Type": "overlay",
"Source": "overlay",
"Target": "",
"Options": [
"lowerdir=/var/lib/containerd-nydus/snapshots/510/mnt:/var/lib/containerd-nydus/snapshots/536/fs"
]
}
]
```
=> support nydus image topmost layer view

.github/workflows/optimizer.yml, cmd/optimizer-nri-plugin/main.go, docs/optimize_nydus_image.md, misc/example/optimizer-nri-plugin.conf, pkg/fanotify/conn/conn.go, pkg/fanotify/fanotify.go, pkg/utils/display/display.go, tools/optimizer-server/src/main.rs
1. To avoid using too much memory in the `containerd` cgroup, we should send event information one by one.
2. Add an option to make the result human-readable.
3. Refine the code to better handle errors on the optimizer server.
=> Avoid optimizer to use too much memory and improve error handling processes

pkg/filesystem/fs.go, pkg/referrer/manager.go, pkg/referrer/referrer.go, pkg/snapshot/storage.go, snapshot/process.go, snapshot/snapshot.go
Currently, Buildkit only supports using stargz as the base image remote snapshotter to build container images with lazy-load capability.  This PR is the precondition of adding such capability to Buildkit for nydus-snapshotter, majorly including bugfixes and enhancements.
=> Support using nydus-snapshotter as Builkdit's oci-woker-snapshotter to gain lazyload when building images

pkg/converter/convert_unix.go, pkg/converter/types.go
Limit the maximum size of "Table of Content" in nydus data blobs, to protect nydus-snapshotter from possible DoS attack.
=> Limit the maximum size of "Table of Content" in nydus data blobs

cmd/containerd-nydus-grpc/main.go, cmd/containerd-nydus-grpc/snapshotter.go, config/config.go, config/global.go, internal/flags/flags.go
Refine command line help messages and error messages.
=> cmd: refine command line help messages and error messages

.github/codecov.yml
In order to improve the code quality of this project, we have introduced a test coverage check in CI to prevent code with low unit test coverage from being merged. Although there is no perfect code coverage value, we can still make a stab at such a value. 3 years ago, Google posted a [blog post](https://testing.googleblog.com/2020/08/code-coverage-best-practices.html) on their best practices:
> We offer the general guidelines of 60% as “acceptable”, 75% as “commendable” and 90% as “exemplary.”
Therefore, in order to increase the overall code coverage of this project to 60% mentioned in #334, we set the coverage of each patch to 75% and above.
Patch details:
1. The project's unit test coverage cannot be reduced by more than 0.5%.
2. The unit test coverage of each patch must be higher than …
=> action: update workflow to block low unit test coverage code

cmd/containerd-nydus-grpc/main.go, config/config.go, config/config_test.go, config/default.go, internal/constant/values.go, internal/flags/flags.go, pkg/daemon/config.go
- pkg: introduce internal/constant package 
- cmd: improve user interface for help message by add default text
Current help message:
``` 
NAME:
containerd-nydus-grpc - Nydus remote snapshotter for containerd
USAGE:
containerd-nydus-grpc [global options] command [command options] [arguments...]
COMMANDS:
help, h  Shows a list of commands or help for one command
GLOBAL OPTIONS:
--root value                                directory to store snapshotter data and working states (default: /var/lib/containerd-nydus)
--address value                             remote snapshotter gRPC socket path (default: /run/containerd-nydus/containerd-nydus-grpc.sock)
--config value                              path to nydus-snapshotter configuration (such as: config.toml)
--nydus-image nydus-image …
```
=> cmd: improve user interface for help message by add default text

pkg/cache/manager.go, snapshot/snapshot.go
The FsDriver field is never used, so remove it.
=> cache: simplify cache manager by removing FsDriver

.github/workflows/optimizer.yml, misc/optimizer/nginx.yaml, misc/optimizer/sandbox.yaml, misc/optimizer/ubuntu.yaml
We use `nginx:1.23.3` to test the optimizer, but sometimes the number of files accessed is not equal to 44. Normally, the optimizer works fine if the number of files accessed is greater than 0.
=> workflow: fix incorrect files number for optimizer test

pkg/converter/convert_unix.go
When we convert nydus with empty blob data to gzip
(or other compression types) layer, will encounter the error:
```
unpack nydus blob: unpack nydus tar: unpack blob from nydus:
can't find target image.blob by seeking tar: data not found
```
The nydus layer may contain only bootstrap and no blob
data, which should be ignored.
=> converter: ignore nonexistent blob data for unpack

.github/codecov.yml
In the recent PR #482, the patch coverage requirement seems to be too strict. So we temporarily remove this check and focus on project coverage.
=> action: remove patch coverage check in workflow

Makefile, tools/optimizer-server/Makefile, tools/optimizer-server/src/main.rs
1. Add its own makefile and invokes the makefile from the project root makefile
2. No need to use libc integer types, the standard integer types meet our reuqiurements
=> Minor improvements for image optimizer

pkg/converter/convert_unix.go, pkg/converter/tool/builder.go, pkg/converter/tool/feature.go, pkg/converter/tool/feature_test.go
1. Change the way to detect features by checking help message of `nydus-image create -h`.
2. Add feature detection for `--batch-size` to keep compatibility with old versions of nydus-image.
For old versions of `nydus-image`:
```shell
runner@nyd:~/work/image-service/image-service$ sudo contrib/nydusify/cmd/nydusify convert --source dockerhub.kubekey.local/nydus/node:19-alpine --target dockerhub.kubekey.local/nydus/node:19-alpine-nydus-batch-1M --target-insecure --source-insecure --batch-size 0x100000 log-level trace
INFO[2023-06-06T12:43:00+08:00] pulling image dockerhub.kubekey.local/nydus/node:19-alpine  module=converter
INFO[2023-06-06T12:43:04+08:00] pulled image dockerhub.kubekey.local/nydus/node:19-alpine, elapse 3.254672243s  module=converter
INFO[2023-06-06T12:43:04+08:00] …
```
=> converter: add feature detection for `--batch-size`

integration/Dockerfile
We don't need this proxy, so remove it.
=> integration: remove GOPROXY environment

MAINTAINERS
Bin Tang @sctb512 has worked as a nydus-snapshotter developer for almost one year. He has contributed valuable features to the project and mastered the core design philosophy and essential working process. Those features include:
1. logger builder
2. metrics collector
3. mirror registry support
4. maintenance infrastructure
5. nydus image optimizer and related containerd NRI plugin
6. nydusd daemon resources manager
7. other misc test works
The features help a lot for the project to grow. Thanks for his remarkable work
I'd like to invite him as a nydus-snapshotter reviewer if he would approve :)
Needs explicit LGTM from @sctb512 and 1/3 of the nydus-snapshotter committers:
=> add Bin Tang as a reviewer

config/config.go, config/default.go, config/global.go, internal/constant/values.go, pkg/daemon/config.go, pkg/daemon/rafs.go, pkg/filesystem/config.go, pkg/filesystem/fs.go, pkg/manager/manager.go, pkg/manager/monitor.go, pkg/manager/monitor_test.go, snapshot/snapshot.go
Enhance the snapshotter to prepare for
- running nydusd daemon on multiple modes concurrently: fusedev shared, fusedev dedicated, fscache
- support tarfs
=> Prepare to support multiple running modes and tarfs

.github/codecov.yml
It messes up the PR code change page.
=> don't let codecov tool comment everywhere in PR

pkg/converter/constant.go, pkg/converter/convert_unix.go, pkg/converter/tool/builder.go, pkg/converter/tool/feature.go, pkg/converter/tool/feature_test.go, pkg/converter/types.go
support encrypting nydus data blobs
Related [issue](https://github.com/dragonflyoss/image-service/issues/1334)
=> feats: support encrypting nydus data blobs

.github/workflows/release.yml
https://github.com/containerd/nydus-snapshotter/actions/runs/5584824903
The hub has been [integrated](https://github.com/mislav/hub#github-actions) to github action worker, so let's remove it to fix the failure.
A successful action example can be found here: https://github.com/imeoer/nydus-snapshotter/actions/runs/5586816647
=> action: remove the broken step of installing hub

README.md, config/daemonconfig/daemonconfig.go, config/daemonconfig/mirrors.go, config/daemonconfig/mirrors_test.go
We have removed the `auth_through` option in https://github.com/dragonflyoss/image-service/pull/1375
Let's remove it in snapshotter, since its default value is false, there is no compatibility impact.
=> config: remove useless auth_through option

pkg/filesystem/fs.go
This patch allows the snapshotter resumes the recovering nydusd daemons parallelizilly in the starting stage.
fix #505
=> optimize: resume nydusd processes parallelizilly

pkg/converter/constant.go, pkg/converter/convert_unix.go
Add remote cache of remote registry.
Changes:
- Skip conversion if layer cache exists.
- Add two LayerAnnotation  as constant labels
=> feat: prevent unnecessary conversions

config/config.go, config/global.go, docs/tarfs.md, go.mod, go.sum, misc/snapshotter/config.toml, pkg/cache/manager.go, pkg/filesystem/config.go, pkg/filesystem/fs.go, pkg/filesystem/tarfs_adaptor.go, pkg/label/label.go, pkg/manager/manager.go, pkg/metrics/serve.go, pkg/snapshot/storage.go, pkg/tarfs/tarfs.go, snapshot/mount_option.go, snapshot/process.go, snapshot/snapshot.go
This PR is based on https://github.com/containerd/nydus-snapshotter/pull/497 , and improve tarfs by:
- move loopdev setup from Prepare()/Merge() into Mount(), preparing for support of nodev mode in addition to blockdev.
- store tar file in the global cache directory, mount tarfs at "mnt" instead of "tarfs", to keep consistence with fusedev/fscache drivers.
- use tempfile/rename mechanism to easy error recover
- use lock to avoid some possible race conditions
- use mode 0750 instead of 0755 for new directories
-  associate a Manager with filesystems managed by blockdev
=> Refine tarfs overall design and implementation details

.github/workflows/release.yml, Makefile, cmd/nydus-overlayfs/main.go
Nydus-overlayfs is a mount helper for nydus-snapshotter, and is only used by nydus-snapshotter. So move it from Image Service into nydus-snapshotter.
=> cmd: move nydus-overlayfs from image service to snapshotter

pkg/daemon/daemon.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/monitor.go
In the faileover process, if the new daemon is unexpectedly killed before the new daemon is subscribed to by monitor, the manager will not retry to start the daemon to ensure that the new daemon runs successfully.
In this PR, the manager will retry to start the daemon if the process is not running.
Test command:
```shell
for i in $(seq 500);do ps -ef | grep nydusd| grep -v grep | awk '{print $2}'|xargs kill -9;sleep 0.01; done
```
Expected result: all nydusd will eventually recover.
=> Manager: make nydusd daemon reach desired state

config/config.go, config/global.go, internal/constant/values.go, misc/snapshotter/config-coco-guest-pulling.toml, misc/snapshotter/config-coco-host-sharing.toml, misc/snapshotter/config.toml, pkg/filesystem/config.go, pkg/filesystem/fs.go, pkg/filesystem/tarfs_adaptor.go, pkg/label/label.go, pkg/manager/manager.go, pkg/metrics/serve.go, pkg/tarfs/tarfs.go, snapshot/mount_option.go, snapshot/mount_option_test.go, snapshot/process.go, snapshot/snapshot.go
Support host sharing and guest pulling for Confidential Container image management:
- import a `KataVirtualVolume` structure, which acts as a superset of `ExtraOptions`
- support build a disk image for a container image with EROFS and passing disk image info to kata-runtime through `KataVirtualVolume`.
- support downloading container image inside guest by introducing `proxy` mode, which doesn't download any layer content on host but only insert a `KataVirutalVolume` into `Mount.Options`.
This PR is based on #528
=> Support host sharing and guest pulling for Confidential Container image management

pkg/daemon/daemon.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/monitor.go
Revert https://github.com/containerd/nydus-snapshotter/pull/531 
If nydusd is not subscribed and is unexpectedly killed, send an event to the death event handler.
=> manager: avoid to start daemon in dead loop 

pkg/converter/convert_windows.go
Previously, the function signatures differed after being updated in b16a06858426dd2034bc361cb29805734e32d7c3. This patch updates the corresponding windows functions to match the linux signatures.
Discovered this in BuildKit when attempting to enable linting for Windows: https://github.com/moby/buildkit/pull/4261
=> fix: update windows public functions to match linux

integration/entrypoint.sh
Github action has upgraded its worker kernel to 6.2 with CONFIG_EROFS_FS_ONDEMAND enabled. The e2e tests of failover depends on private kernel patches rather upstream kernel. So we have to totally disable the failover tests for now
=> e2e: always disable erofs ondemand-read test and failover test

.github/workflows/optimizer.yml
This PR try to fix the error that contained is not ready when generating accessed files list in optimizer test.
The error is:
```
time="2023-09-21T10:06:07Z" level=fatal msg="running container: run pod sandbox: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
```
=> workflow: fix containerd not ready error for optimizer test

misc/snapshotter/config.toml, pkg/cache/manager.go, snapshot/snapshot.go
Filesystem.cacheMgr is null when cacheManager.Disable is configured to be true, thus cause null pointer access. Fix it by always create the cacheMgr object no matter cacheManager.Disable is true or false.
=> cache: fix null pointer access when cachemanager.Disable is true

pkg/converter/convert_unix.go, pkg/converter/types.go, pkg/encryption/encryption.go, tests/converter_test.go
```
Due to the introduction of the github.com/containers/ocicrypt package
in converter, which brings in many other dependencies, but encryption
should currently be an experimental optional feature, we need to move
this part of the codes out to reduce the burden on other projects that
reference the package.
```
Ref: https://github.com/moby/buildkit/pull/4288
=> converter: move out encryption package

pkg/converter/convert_unix.go
We should also add the labels.LabelUncompressed label and the
label.NydusRefLayer, LayerAnnotationNydusEncryptedBlob annotations
for the layer in content store cache, otherwise the generated
layer descriptor is invalid for acceld/nydusify.
=> converter: fix invalid layer desc when cache hits

pkg/converter/convert_unix.go
We should also add the labels.LabelUncompressed label and the
label.NydusRefLayer, LayerAnnotationNydusEncryptedBlob annotations
for the layer in content store cache, otherwise the generated
layer descriptor is invalid for acceld/nydusify.
=> [backport v0.13] converter: fix invalid layer desc when cache hits

pkg/converter/convert_unix.go
dir-rafs lacks the `batch-size` build parameter,
making the converting failed when tar-rafs is disabled and fallbacked to dir-rafs
=> converter: fix missed BatchSize arg for dir-rafs packing

pkg/converter/convert_unix.go
dir-rafs lacks the `batch-size` build parameter,
making the converting failed when tar-rafs is disabled and fallbacked to dir-rafs
=> [backport v0.13] converter: fix missed BatchSize arg for dir-rafs packing

config/config.go, config/daemonconfig/daemonconfig.go, config/daemonconfig/daemonconfig_test.go, config/global.go, misc/snapshotter/config.toml, pkg/daemon/command/command.go, pkg/manager/daemon_adaptor.go, pkg/system/system.go
[https://github.com/containerd/nydus-snapshotter/issues/388](url)
- Add interface endpointGetDaemonConfig string="/api/v1/daemons/{id}/config" in system. go
- Add handler func getDaemonConfig() to deliver config
- Pass the system socket and URL to nydusd through command-line arguments
=> Adding an interface to the system socket to help nydusd obtain config

config/daemonconfig/daemonconfig_test.go, config/daemonconfig/fuse.go, misc/snapshotter/nydusd-config-localfs.json, misc/snapshotter/nydusd-config.fusedev.json, pkg/stargz/testdata/config/nydus.json, tests/e2e/k8s/snapshotter-cri.yaml, tests/e2e/k8s/snapshotter-kubeconf.yaml, tests/nydusd.go
Add `amplify_io` support, by reading and forwarding this arg.
`amplify_io` is an arg supported by nydusd to configure read amplification.
Related PR: https://github.com/dragonflyoss/nydus/pull/1452
=> daemon: add `amplify_io` support in nydusd configuration file

config/daemonconfig/daemonconfig_test.go, config/daemonconfig/fuse.go
`amplify_io` should be nullable in config file.
The absence of `amplify_io` in the config file means it follows the default value in nydusd, i.e., 1M.
`amplify_io=0` means it is set to zero.
So let's change this field into nullable to pass the value as what it is read from template config file.
=> daemon: change `amplify_io` into nullable int

.github/workflows/release.yml
In our released nydus-snapshotter images, the nydusd version is always v2.1.5, and this patch fixes that.
=> release: get latest nydusd version from Github API

pkg/filesystem/tarfs_adaptor.go, pkg/tarfs/tarfs.go, snapshot/mount_option.go, snapshot/process.go, snapshot/snapshot.go
Nydus snapshotter supports both image block and layer block modes, with or without dm-verity. However, for confidential containers, nydus-snapshotter only supports image block mode, with or without dm-verity. Therefore, we need to extend nydus-snapshotter to support layer block mode, with or without dm-verity, for confidential containers as well.
options example for pulling `docker.io/library/nginx:latest `
```       
workdir=/var/lib/containerd-nydus/snapshots/8/work upperdir=/var/lib/containerd-nydus/snapshots/8/fs lowerdir=/var/lib/containerd-nydus/snapshots/7/fs
io.katacontainers.volume=eyJ2b2x1bWVfdHlwZSI6ImxheWVyX3Jhd19ibG9jayIsInNvdXJjZSI6Ii92YXIvbGliL2NvbnRhaW5lcmQtbnlkdXMvY2FjaGUvNTE3MzU3ODMxOTY3ODVkMWY2MDRkYzc3MTFlYTcwZmIzZmFiM2NkOWQ5OWVhZWZmOTkxYzVhZmJmYTBmMjBlOC5sYXllci5kaXNrIi …
```
=> Support sharing image on the host for layer block mode

docs/run_nydus_in_kubernetes.md
Supplementary for containerd configuration required by nydus snapshotter: `disable_snapshot_annotations` and
`discard_unpacked_layers`.
=> docs: Supplementary for containerd configuration required by snapshotter

.github/workflows/release.yml, Makefile
Fixed the asset link in github release page from
`nydus-snapshotter-x.x.x-linux-amd64.tar.gz` to `nydus-snapshotter-vx.x.x-linux-amd64.tar.gz`
Tested release: https://github.com/imeoer/nydus-snapshotter/releases/tag/v0.13.8
=> action: fix incorrect release asset link

.github/workflows/release.yml
The nydus latest reelase version should be got from dragonfly/nydus repo.
Tested CI: https://github.com/imeoer/nydus-snapshotter/actions/runs/7709106171/job/21009677183
=> action: fix failed image build

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/k8s-e2e.yml, .github/workflows/optimizer.yml, config/daemonconfig/fuse.go, pkg/auth/image_proxy_test.go, pkg/auth/keychain.go, pkg/daemon/daemon.go, pkg/filesystem/fs.go, pkg/filesystem/stargz_adaptor.go, pkg/metrics/serve.go, pkg/rafs/rafs.go, pkg/remote/remote.go, pkg/remote/unpack.go, pkg/stargz/resolver_test.go, pkg/store/database.go, pkg/store/database_compat.go, pkg/system/system.go, pkg/utils/erofs/erofs.go
1. use `nodejs 20` version action: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ .
2. update golangci-lint v1.55.2 and use official GitHub action for [golangci-lint](https://github.com/golangci/golangci-lint).
3. use setup-go @v5 native cache ability.
4. fix lint errors.
=> action: update nodejs20

.github/workflows/ci.yml, cmd/containerd-nydus-grpc/main.go, cmd/optimizer-nri-plugin/main.go, cmd/prefetchfiles-nri-plugin/main.go, internal/logging/setup_test.go, pkg/auth/kubesecret.go, pkg/converter/convert_unix.go, pkg/daemon/client_test.go, pkg/remote/remote.go, pkg/system/system.go, pkg/utils/retry/retry.go, pkg/utils/transport/pool_test.go, snapshot/snapshot.go, tests/converter_test.go
Ref: https://github.com/golangci/golangci-lint-action/issues/953.
=> chore: bump golangci-lint-action v4

.github/workflows/release.yml
This commit is to build and release `ghcr.io/containerd/nydus-snapshotter` for multiple platforms (below) by leveraging GHA's QEMU/buildx funtionalities.
- amd64
- arm64
- s390x
- ppc64le
The workflow was verified and the image is available at https://github.com/BbolroC/nydus-snapshotter/pkgs/container/nydus-snapshotter/179477460?tag=enable-multi-arch-image.
Fixes: #583
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>
=> action: enable nydus-snapshotter image to support multi-arch

.github/workflows/release.yml
The PR #584 overlooked a scenario involving more than two elements in `steps.meta.outputs.tags`. This commit addresses that by iterating over the tags and creating/pushing a manifest for them, respectively.
Fixes: #583
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>
=> action: publish manifest for multiple tags

misc/snapshotter/snapshotter.sh
When performing the cleanup with k3s / rke2, we must specify the containerd socket address that's been created by them, instead of using the default one.
For both k3s and rke2 the containerd address socket is the same: `/run/k3s/containerd/containerd.sock`.
=> misc: Fix cleanup with k3s / rke2

pkg/converter/convert_unix.go, pkg/converter/types.go, pkg/converter/utils.go, tools/optimizer-server/Cargo.lock, tools/optimizer-server/Cargo.toml, tools/optimizer-server/src/main.rs
Support `AppendFiles` option on `converter.Merge` method,
`AppendFiles` specifies the files that need to be appended
to the bootstrap layer.
This option allows the user to place some files in the nydus
bootstrap layer, for example, the user can place metadata
info generated at build time, e.g. named `image/metadata.json`.
And this usage does not affect the `image/image.boot` bootstrap
file that is accessed by the nydus runtime.
=> converter: support appending files to bootstrap layer

docs/optimize_nydus_image.md
The documentation incorrectly stated that the result file for the nginx image is located at `/opt/nri/optimizer/results/nginx:latest`. However, the correct file path is `/opt/nri/optimizer/results/library/nginx:latest`.
=> docs: fix incorrect file path for nginx result file

misc/snapshotter/Dockerfile
Let's use Docker's `COPY --chmod` feature instead of using a separate chmod command. This will reduce the generated image size by ~12KB.
Fixes: #402
=> misc: merge chmod into copy in Dockerfile

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/k8s-e2e.yml, .github/workflows/optimizer.yml, .github/workflows/release.yml, Makefile, go.mod, integration/Dockerfile, integration/entrypoint.sh, misc/snapshotter/Dockerfile
Work on #604 required a set of changes, fixes and updates to the test rig and CI, and has grown really large.
This PR does split out some of the more minor changes to make it easier to review.
Furthermore, the CI is in a shaky state right now and is just red, as the build fails because of delve latest being dependent on a more recent version of go (which in turns requires a series of changes), and also as #603 seems to break e2e kube tests (or this test is very flaky).
Changes:
- quiet apk, apt-get, wget and curl to make the logs less noisy and easier to read
- update github actions to their latest versions
- update golang to 1.21 - delve requires it - also, go 1.23 is soon to be out - and containerd v2 requires 1.22
- remove no longer useful variables
- increase sleep after kill to avoid …
=> CI fix, part I: update and cleanup

misc/snapshotter/snapshotter.sh
Cleanup never happening for these directories.
Regex not evaluated in the rm statement.
=> cleanup: regex not being evaluated in quoted expression

misc/snapshotter/snapshotter.sh
The cleanup process exits before completion. In addition to snapshots, we also need to clean up related content and images.
Depends on Ryan's PR #605.
=> misc: remove related images/contents/snapshots in cleanup progress 

config/config.go, go.mod, go.sum
- relates to https://github.com/containerd/containerd/pull/9569
The module was renamed to dario.cat/mergo. The old dependency isn't fully gone yet, because kubernetes still uses the old location, but that may go away eventually; https://github.com/kubernetes/client-go/blob/v0.26.2/go.mod#L18
full diff: https://github.com/darccio/mergo/compare/v0.3.13...v1.0.0
=> go.mod: dario.cat/mergo v1.0.0

pkg/auth/image_proxy.go, pkg/auth/image_proxy_test.go
- relates to https://github.com/containerd/stargz-snapshotter/pull/1175
CRI v1alpha2 is deprecated since containerd 1.7:
https://github.com/containerd/containerd/blob/v1.7.0/RELEASES.md#deprecated-features
=> pkg/auth: remove CRI Alpha API

pkg/supervisor/supervisor.go, pkg/supervisor/supervisor_test.go
```
When the supervisor needs to process a large amount of opaque data (for example,
a nydusd instance has a large number of sub mounts, and the opaque is usually
larger than 32kb), a recvmsg / sendmsg system call cannot process all data.
The commit fixes the problem with multiple recvmsg/sendmsg calls and updates
the test cases.
```
=> supervisor: fix large opaque data handle

config/config.go, config/config_test.go, internal/flags/flags.go, misc/snapshotter/config.toml, snapshot/mount_option.go, snapshot/snapshot.go
This allows installation of multiple nydus-overlayfs versions on the same machine.
=> snapshotter: add flag to specify nydus-overlayfs path

misc/snapshotter/Dockerfile, pkg/cache/manager.go, tests/helpers/helpers.sh
Nydus latest chunk_map path has changed to `{blob_id}.blob.data.chunk_map`. Add `blobChunkMapSuffixedPath` to keep backward compatibility.
=> fix: update chunkmap suffix

misc/snapshotter/Dockerfile, tests/helpers/kind.sh
nydus v2.3.0 released: https://github.com/dragonflyoss/nydus/releases/tag/v2.3.0
=> upgrade nydus version to v2.3.0 in test

pkg/converter/tool/builder.go, tests/converter_test.go
This patch modifies the unpack testcase to keep consistent with the new `nydus-image unpack` interface in nydus-image.
=> tests/converter: modify unpack testcase

config/daemonconfig/daemonconfig.go, config/daemonconfig/fscache.go, config/daemonconfig/fuse.go, misc/snapshotter/Dockerfile, pkg/daemon/daemon.go, pkg/filesystem/fs.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/store.go, pkg/store/daemonstore.go, pkg/store/database.go, tests/helpers/helpers.sh
- Modify operations to use memory instead of disk
=> Remove DumpFile operations

pkg/fanotify/fanotify.go, tools/optimizer-server/src/main.rs
Based on the process outlined in [optimize_nydus_image](https://github.com/containerd/nydus-snapshotter/blob/main/docs/optimize_nydus_image.md), we attempted to build an optimizer to generate the accessed files list. The optimizer-server and optimizer-nri-plugin were deployed on the server. After some time, we noticed that some of the optimizer-servers became defunct. The specific screenshots are as follows:
The parent processes of these zombie processes all belong to the optimizer-nri-plugin. We have also verified that this issue occurs on every server we deployed. 
We believe that if the servers continue to retain these zombie processes, they will accumulate to a certain number and eventually affect the normal operation of the business.
We checked and found that the issue primarily lies …
=> Dealing with optimizer-server zombie processes

README.md
This pull request includes a small but important change to the `README.md` file. The change corrects the URL for the Dragonfly project to its proper location.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L143-R143): Corrected the URL for the Dragonfly project from `https://github.com/dragonflyoss/Dragonfly2` to `https://github.com/dragonflyoss/dragonfly`.
Refer to https://github.com/dragonflyoss/dragonfly/issues/3714.
=> docs: rename repo Dragonfly2 to dragonfly

tools/optimizer-server/src/main.rs
This change fixes the compilation error in CI, allowing the  optimizer-server build to pass.
=> [Fix] resolve clippy::uninlined_format_args warning in optimizer-server

tests/helpers/kind.sh, tests/helpers/lib.sh
In the kind.sh script, after the local Docker registry container starts, the http::healthcheck function attempts to connect to the registry service. We've observed that in CI environments, the service within the registry container sometimes takes several seconds to start listening on the port, causing curl to return a "Connection refused" error on the first health check attempt.
By default, curl treats "Connection refused" as a non-retryable error and exits immediately, rather than waiting as specified by the --retry flag. This causes the CI process to fail prematurely before the service is ready, leading to instability.
To make the CI process more robust, this change :
- increases the number of retries and delay for the http::healthcheck function in the kind.sh script.
- added …
=> [Fix] increase registry healthcheck retries to improve CI stability

pkg/daemon/daemon.go, pkg/system/system.go
For daemons that have been hot upgraded, subsequent rmi mirroring cannot clear the daemons.
This pr optimizes this.
=> [Optimize] improve the stability of hot upgrade daemon process

pkg/system/system.go
The use of os.Rename (which has mv semantics) would cause the file at the original source path (newNydusdPath) to no longer exist after the hot upgrade operation.
=> [Fix] proper handling of nydusd binary copies in hot upgrades

pkg/converter/convert_unix.go
Read any trailing data for some tar formats, in case the PipeWriter of opposite side gets stuck.
Reference: https://github.com/containerd/containerd/blob/6373c7b53b76db25365824d3c969c409e630cf02/core/diff/apply/apply.go#L99
=> converter: fix trailing data after applying archive

pkg/backend/s3.go, pkg/backend/s3_test.go
This PR adds a configuration option to set the checksum algorithm for S3-compatible backends, specifically to resolve 500 errors when uploading to Cloudflare R2.
Add a new parameter "checksum_algorithm" to the json config for the s3backend. This enables using different checksum algorithms or to disable checksums entirely by passing "". This is needed for multipart uploads to work with cloudflare r2 since they don't support the `x-amz-checksum-algorithm` parameter in UpdatePart messages.
=== RUN   Test_newS3Backend
=== RUN   Test_newS3Backend/test1,_no_error
=== RUN   Test_newS3Backend/test2,_set_checksum_algorithm
--- PASS: Test_newS3Backend (0.00s)
--- PASS: Test_newS3Backend/test1,_no_error (0.00s)
--- PASS: Test_newS3Backend/test2,_set_checksum_algorithm (0.00s)
PASS
ok …
=> Add configurable checksum for s3 backend to enable cloudflare r2 support
