containerd/nydus-snapshotter

README.md
The links are not valid anymore, this fixes them to work.
Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com>
=> Fix stale links of docs

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, pkg/daemon/config.go, pkg/daemon/daemon.go, pkg/filesystem/nydus/config.go, pkg/filesystem/nydus/fs.go, pkg/filesystem/stargz/config.go, pkg/filesystem/stargz/fs.go, pkg/process/manager.go, snapshot/snapshot.go
Use a user configurable for thread-num than a fixed value.
Fixes: #19
=> make thread-num for nydusd should be configurable

Makefile, go.mod, go.sum
=> deps: update docker/distribution and opencontainers/image-spec

.github/workflows/ci.yml, .github/workflows/image.yml, .github/workflows/release.yml
Use `softprops/action-gh-release` to raise new releases. See https://github.com/bergwolf/nydus-snapshotter/actions/runs/2108686687 for a working example.
=> action: optimize release

pkg/process/manager.go
For shared daemon mode, we should first umount for virtual daemon,
and then cleanup daemon resource (config, log) and the daemon info
in store, otherwise we can't umount once the config be removed,
because in the erofs scenario, we need to rely on the domain id
recorded in the config to request the daemon to unbind the blob
resources.
=> process: fix shared umount on daemon destroy

.github/workflows/release.yml
Allow to publish release version by tag like v0.3.0-alpha.0.
=> action: relax the condition of release tag

README.md
Also add some words for stargz.
Signed-off-by: Gao Xiang \<hsiangkao@linux.alibaba.com\>
=> README.md: improve the overall description

pkg/auth/keychain.go, pkg/auth/keychain_test.go, pkg/label/handler.go, pkg/label/label.go, pkg/signature/signature.go, snapshot/snapshot.go
Fix a bug in annotation preparation and also refine annotation names.
=> Fix a bug in annotation preparation

cmd/containerd-nydus-grpc/app/snapshotter/serve.go, cmd/containerd-nydus-grpc/pkg/command/flags.go, pkg/process/manager.go, snapshot/snapshot.go
Several enhancements:
1) enable log for fscache
2) avoid deleting non-socket file when removing old socket file
3) refine error handling logic in createSnapshot
=> Enable log for fscache

pkg/filesystem/fs/resolver.go, pkg/filesystem/fs/stargz/resolver.go, pkg/filesystem/fs/stargz/resolver_test.go, pkg/utils/transport/pool.go, pkg/utils/transport/pool_test.go
1. use common resolver for localfs mode and startgz
2. fix download blobs don't auth for localfs mode
Signed-off-by: zyfjeff <zyfjeff@linux.alibaba-inc.com>
=> Refactor resolver and fix download blob bug for localfs mode

pkg/converter/convert_unix.go
=> converter: fix some comments

.github/workflows/image.yml, misc/snapshotter/entrypoint.sh
Now only shared daemon mode is performed. Also do it
for multipe daemon mode.
=> github: perform test against multiple daemon mode

cmd/containerd-nydus-grpc/pkg/command/flags.go
Thus to keep consistent with /run/containerd-nydus
=> change default work root dir to /var/lib/containerd-nydus

pkg/converter/convert_unix.go
In case users forget to create the work directory before using converter.
=> converter: create work directory if not exists

pkg/converter/convert_unix.go
Write a diff id label of layer in content store for simplifying
diff id calculation to speed up the conversion.
See: https://github.com/containerd/containerd/blob/e4fefea5544d259177abb85b64e428702ac49c97/images/diffid.go#L49
Related performance test: https://github.com/goharbor/acceleration-service/pull/50
=> converter: improve performance by calculating diffid ahead of time

pkg/converter/convert_unix.go, pkg/converter/convert_windows.go
Make them easier for buildkit/nerdctl/acceld components to use.
=> converter: export IsNydusBlob and MergeLayers methods

pkg/filesystem/fs/fs.go, snapshot/snapshot.go
NoneMode nydus-snapshotter does not start nydusd and
no container image mounted contents are provided. Only
info in mount options are meaningful. So give a dummy
mount dir there.
=> give NoneMode mount option with lowerdir=/dummy

cmd/containerd-nydus-grpc/pkg/logging/setup_test.go
=> clean up test purpose log directory

pkg/converter/convert_unix.go, tests/converter_test.go
add buffer for io.Writer to improve
nydus image conversion performation.
This PR is addressing #128 
=> converter: add buffer for io.Writer

pkg/filesystem/fs/fs.go
=> close file after opened and written

integration/Dockerfile, integration/entrypoint.sh, pkg/daemon/daemon.go, pkg/process/manager.go
Support recover those nydusd daemon that started in fscache driver
=> Fscache recover

integration/entrypoint.sh
nydus-snapshotter is compatible with overlayfs snapshotter, add a test for it
=> add e2e test for nydus-snapshotter OCI/overlayfs compatibility

cmd/containerd-nydus-grpc/main.go
=> print process PID and program version to log

config/daemonconfig.go
relates to https://github.com/dragonflyoss/image-service/pull/759
=> support configure nydusd with use_http

cmd/containerd-nydus-grpc/main.go, cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, docs/configure_nydus.md, go.mod, go.sum
Use the toml file to configure the startup parameters of nydus-snapshotter
relates to https://github.com/containerd/nydus-snapshotter/pull/178
Signed-off-by: raoxiang [raoxiang1996@gmail.com](mailto:raoxiang1996@gmail.com)
=> start nydus by toml config

pkg/daemon/daemon.go, pkg/daemon/types/types.go, pkg/filesystem/fs/fs.go, pkg/metric/exporter/export.go, pkg/metric/exporter/metrics.go, pkg/metric/exporter/types.go, pkg/nydussdk/client.go, pkg/nydussdk/client_test.go, pkg/nydussdk/model/model.go, pkg/process/manager.go
Extract several helper functions to decode http reponse, construct HTTP URL with the capability to accommodate  query string
=> refactor nydusd http client package

cmd/containerd-nydus-grpc/main.go, config/config.go, integration/entrypoint.sh, pkg/daemon/daemon.go, pkg/errdefs/errors.go, pkg/filesystem/fs/config.go, pkg/filesystem/fs/fs.go, pkg/manager/manager.go, snapshot/snapshot.go
We should give a explicit error if daemon mode argument is not legal.
=> Validate daemon mode

pkg/daemon/client.go, pkg/daemon/daemon.go, pkg/daemon/types/types.go, pkg/metrics/exporter/export.go, pkg/metrics/exporter/metrics.go, pkg/metrics/exporter/types.go, pkg/metrics/serve.go
FsMetrics is more suggestive. No logic was changed within this PR
=> rename FsMetric to FsMetrics across the project

config/daemonconfig.go, pkg/utils/erofs/erofs.go
This reverts commit f2f36e99feb8f49890def76e14f59be14382cc9a.
=> Revert "support global shared domain"

pkg/daemon/command/command.go
Also recognize --id parameter when building the command line
=> command builder recognize id parameter

go.mod
The were published by accident.
=> retract some published module versions

integration/entrypoint.sh, pkg/cache/manager.go, pkg/filesystem/fs/fs.go, snapshot/snapshot.go
=> Port snapshots usage

Makefile, integration/Dockerfile, integration/entrypoint.sh, pkg/daemon/daemon.go, pkg/errdefs/errors.go, pkg/filesystem/fs/fs.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/mode.go, pkg/supervisor/supervisor.go, pkg/supervisor/supervisor_test.go, pkg/utils/mount/mount.go, snapshot/snapshot.go
Provide a framework to manage nydusd running states and hold its various resources.
=> Introduce supervisor to manage nydusd runtime states and hold resources

config/daemonconfig.go
Backport nydus mirror health checking patch to stable/v0.3
Related to https://github.com/containerd/nydus-snapshotter/pull/217
=> add mirror health checking

integration/Dockerfile, integration/entrypoint.sh
=> remove registry mirror urls

pkg/daemon/client.go, pkg/daemon/daemon.go, pkg/manager/manager.go
=> simplify nydusd http client initialization

.golangci.yml, config/daemonconfig/daemonconfig.go, pkg/supervisor/supervisor.go, tests/nydusd.go
Don't show config content to other users.
=> don't write config file with permissions greater than 0600

Makefile, cmd/containerd-nydus-grpc/main.go, version/version.go
The correct one shoud be revision
=> fix a typo in version message

.github/workflows/release.yml, misc/snapshotter/Dockerfile, misc/snapshotter/entrypoint.sh
When new release is created, build and push Docker image to GitHub Packages.
Fixe: #237 
=> release: build and push Docker image

README.md
=> move FOSSA license ribbon to the top position

.github/workflows/k8s-e2e.yml
=> Don't return error if test pod is not created or has been deleted

cmd/containerd-nydus-grpc/pkg/command/flags.go, config/config.go, pkg/store/database_compat.go, snapshot/snapshot.go
Clearly backports 2 patches from main branch and prepares to release v0.4.1
=> Backport 0.4

pkg/converter/convert_unix.go, pkg/converter/tool/builder.go, pkg/converter/utils.go, pkg/errdefs/errors.go
To reduce a external package for the users.
=> converter: remove pkg/errdefs dependence

snapshot/snapshot.go
When shared daemon is enabled, snapshot config uses `<daemon id>/<snapshot id>/config.json` now.
Signed-off-by: Li Yuxuan <liyuxuan.darfux@bytedance.com>
=> snapshot:remoteMounts: Load snapshot config under shared mode

pkg/daemon/daemon.go, pkg/daemon/rafs.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go
Provide supervisor to fscache nydusd with a couple of tiny fixes to support fscache based nydusd failover
=> Support fscache nydusd failover

pkg/metrics/data/snapshotter.go
=> metrics: fix incorrect descriptions

.github/workflows/e2e.yml
Add a cron trigger to github action
=> trigger e2e github action everyday

pkg/manager/daemon_adaptor.go, pkg/manager/manager.go
=> metrics: make it atomic for nydusd count

README.md
Add dragonfly twitter badges and update community description.
Signed-off-by: Qinqi Qu <quqinqi@linux.alibaba.com>
=> docs: add badges and update community description

Makefile, config/config_test.go, misc/snapshotter/config.toml, misc/snapshotter/nydus-snapshotter.fscache.service, misc/snapshotter/nydus-snapshotter.fusedev.service
Let nydusd have a minimal number of parameters when being started by systemd.
=> let systemd service adapt the new toml configuration

README.md, cmd/containerd-nydus-grpc/pkg/command/flags.go, misc/snapshotter/entrypoint.sh, tests/e2e/k8s/snapshotter-cri.yaml, tests/e2e/k8s/snapshotter-kubeconf.yaml
=> refine CLI help messages

Makefile
=> Makefile: disable display about mkdir

config/daemonconfig/mirrors.go
=> daemonconfig: remove unused variable

integration/Dockerfile
=> upgrade nydusd version used by e2e test to 2.1.4

pkg/metrics/tool/stat.go, pkg/system/system.go
=> metrics: fix incorrect rss value

README.md, docs/optimize_nydus_image.md
Add a brief introduction section to README and refine the optimizer docs a bit
=> refine containerd nri plugin optimizer docs

integration/entrypoint.sh
1. Fix the test status check that cache dir must be empty
2. Add failover test case for fscache driver
=> Fscache e2e

pkg/converter/convert_unix.go
- Skip to convert the nydus image manifest/index again;
- Handle the situation when the conversion did not occur;
=> [backport] converter: fix handle of manifest index

pkg/converter/convert_unix.go
Associate a reference to the original OCI manifest, see the
`subject` field description in the doc:
https://github.com/opencontainers/image-spec/blob/main/manifest.md#image-manifest-property-descriptions
And if the converted manifest list contains only one manifest,
then convert it directly to manifest.
=> converter: support OCI reference type

misc/snapshotter/config.toml
Remove the unused `log_level` entry in daemon config.
=> misc: remove log level item in daemon config

config/daemonconfig/mirrors.go, config/daemonconfig/mirrors_test.go
=> Do not add server to mirror list

README.md
Follow nydus repo: https://github.com/dragonflyoss/image-service/pull/1183
=> docs: add FAQ, Website and Quickstart link in README.md

pkg/manager/manager.go, pkg/manager/states_cache_test.go
Simplify implementation of DaemonStates by removing field `daemons`.
=> manager: simplify implementation of DaemonStates

config/config.go, config/config_test.go, misc/snapshotter/config.toml
Enforce stricter validation rules and tune default configuration in misc/snapshotter/config.toml
=> config: enforce stricter validation rules and tune default config

pkg/converter/convert_unix.go
Restrict permission of files generated by converter from 0644 to 0640.
=> converter: restrict file permission to 0640

pkg/referrer/referrer.go
Refine implementation of referrer by:
- avoid retry if error is not network related
- limit maximum size of manifest index blob
- remove partially downloaded meta blob
=> referrer: tune implementation details of referrer

cmd/containerd-nydus-grpc/main.go, cmd/containerd-nydus-grpc/snapshotter.go, config/config.go, config/config_test.go, config/default.go, config/global.go, integration/entrypoint.sh, internal/constant/values.go, internal/flags/flags.go, pkg/daemon/config.go, pkg/remote/remote.go, pkg/remote/remotes/docker/auth/fetch.go, pkg/remote/remotes/docker/authorizer.go, pkg/remote/remotes/docker/config/hosts.go, pkg/remote/remotes/docker/config/hosts_test.go, pkg/remote/remotes/docker/converter.go, pkg/remote/remotes/docker/pusher.go, pkg/remote/remotes/docker/pusher_test.go, pkg/remote/remotes/docker/resolver.go, pkg/remote/remotes/docker/resolver_test.go, pkg/remote/remotes/docker/schema1/converter.go
Pick some stable patches from the main branch and prepare to release v0.8.1
=> Prepare 0.8.1

snapshot/process.go, snapshot/snapshot.go
Minor enhancements and bugfixes to snapshot.
=> Minor enhancements and bugfixes to snapshot

pkg/auth/keychain.go, pkg/daemon/client.go, pkg/daemon/command/command.go, pkg/daemon/daemon.go, pkg/daemon/rafs.go, pkg/daemon/types/types.go, pkg/manager/daemon_adaptor.go, pkg/manager/manager.go, pkg/manager/monitor.go, pkg/store/daemonstore.go, pkg/store/database.go, pkg/system/system.go, pkg/utils/transport/pool.go
Minor code style improvements, should be no functional changes.
=> pkg: minor code style improvements

pkg/metrics/serve.go, pkg/system/system.go, snapshot/snapshot.go
Enhance metrics server to support multiple instances of Manager.
=> metrics: prepare to support multiple instances of Manager

pkg/remote/remotes/docker/fetcher.go
Enhance FetchByDigest() to handle manifest with mediatype "application/vnd.oci.image.manifest.v1+json"
Fixes: https://github.com/containerd/nydus-snapshotter/issues/474
=> remote: enhance FetchByDigest() to handle more mediatypes

.github/workflows/optimizer.yml
The optimzer test occasionally fails, let's see what bad happens.
=> dump logs of containerd if optimizer test fails

docs/configure_nydus.md, docs/optimize_nydus_image.md
=> docs: Fix typo

snapshot/process.go
=> snapshot: Fix typo

.github/workflows/ci.yml
Reference to: https://github.com/dragonflyoss/nydus/blob/master/.github/workflows/smoke.yml
=> action: enable CI on stable branch

.github/workflows/release.yml, Makefile, misc/snapshotter/config.toml, tools/optimizer-server/Makefile
Related to https://github.com/containerd/nydus-snapshotter/issues/548
Expected packages: https://github.com/sctb512/nydus-snapshotter/releases/tag/v0.9.2
=> Release nydus-snapshotter packages with different architectures

tests/converter_test.go
=> test: update chunkmap suffix

.gitignore
Adding vendor directory to .gitignore file
=> chore: Add vendor directory in .gitignore file

pkg/filesystem/fs.go, snapshot/mount_option.go
To make nydus-snapshotter work well in CoCo:
(1) Just go pass when do AddRafsInstance failed.
(2) When sn can't get label.CRIImageRef, just assign it with overlayfs.
Signed-off-by: alex.lyn <alex.lyn@antgroup.com>
=> nydus sn: fix issues with "not found" in CoCo cases.

config/daemonconfig/daemonconfig.go
close https://github.com/dragonflyoss/nydus/issues/1706
=> [Chore] adapt to s3 backend

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/improvement-report.yml, .github/PULL_REQUEST_TEMPLATE.md
This PR introduces a multiple-template system for both issues and pull requests, to standardize the contribution process and improve clarity for all contributors.
close https://github.com/dragonflyoss/nydus/issues/1737
=> [Feature] add comprehensive issue and pull request templates

config/daemonconfig/daemonconfig.go, config/daemonconfig/fscache.go, config/daemonconfig/fuse.go
support supplementing workdir for non-registry backends
=> [Chore] support supplementing workdir for non-registry backends

pkg/system/system.go
_Please briefly describe the changes your pull request makes._
correct equality check
Related https://github.com/dragonflyoss/nydus/actions/runs/17579946510/job/49933975851
_Please link to the relevant issue. For example: `Fix #123` or `Related #456`._
_Please describe your changes in detail:_
_If you have any relevant screenshots or videos that can help illustrate your changes, please add them here._
_Please select the type of change your pull request relates to:_
_Before submitting a pull request, please ensure you have completed the following:_
=> [Fix] correct equality check

.gitignore, pkg/daemon/daemon.go, pkg/filesystem/config.go, pkg/filesystem/fs.go, pkg/filesystem/stargz_adaptor.go, pkg/manager/daemon_event.go, snapshot/snapshot.go
Close https://github.com/dragonflyoss/nydus/issues/1698
Close https://github.com/containerd/nydus-snapshotter/issues/632
=> [Feature] support live upgrade for the snapshotter with automation
